import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const sb=createClient("https://vrugwznymkyggijwpprd.supabase.co","sb_publishable_hPmeWT0ZKpJ-H__ZU5FcAA_gptC6L1E");
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let session=null,profile=null;
function modal(html){let m=$('#modal'),b=$('#modalBody');if(m&&b){b.innerHTML=html;m.hidden=false;m.style.display='block'}}
async function load(){let {data}=await sb.auth.getSession();session=data.session;if(session){let r=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=r.data;if(!profile){await sb.from('profiles').insert({id:session.user.id,player_name:session.user.user_metadata?.player_name||session.user.email.split('@')[0]});r=await sb.from('profiles').select('*').eq('id',session.user.id).single();profile=r.data}window.LuxAccount={sb,session,profile};localStorage.setItem('luxcity_last_user',profile.player_name)}}
function authUI(){modal('<h2>Lux City Konto</h2><input id="ae" type="email" placeholder="E-Mail"><input id="ap" type="password" placeholder="Passwort"><input id="an" placeholder="Spielername (bei Registrierung)"><p><button id="ali">ANMELDEN</button> <button id="asu">REGISTRIEREN</button></p><button id="afr">Passwort vergessen?</button><div id="amsg"></div>');let msg=t=>$('#amsg').textContent=t;
$('#ali').onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$('#ae').value.trim(),password:$('#ap').value});msg(error?error.message:'Angemeldet.');if(!error)location.reload()};
$('#asu').onclick=async()=>{let {error}=await sb.auth.signUp({email:$('#ae').value.trim(),password:$('#ap').value,options:{data:{player_name:$('#an').value.trim()||'Spieler'}}});msg(error?error.message:'Konto erstellt. Bitte E-Mail prüfen.')};
$('#afr').onclick=async()=>{let e=$('#ae').value.trim();if(!e)return msg('E-Mail eingeben.');let {error}=await sb.auth.resetPasswordForEmail(e,{redirectTo:location.origin+location.pathname});msg(error?error.message:'E-Mail zum Zurücksetzen wurde gesendet.')}}
async function bankUI(){if(!session)return authUI();let ps=(await sb.from('profiles').select('id,player_name,cash').order('player_name')).data||[];let trs=(await sb.from('bank_transfers').select('*').order('created_at',{ascending:false}).limit(20)).data||[];modal('<h2>🏦 Lux City Bank</h2><p>Kontostand: <b>'+Number(profile.cash).toLocaleString('de-DE')+' €</b></p><select id="to">'+ps.filter(x=>x.id!==session.user.id).map(x=>'<option value="'+x.id+'">'+esc(x.player_name)+'</option>').join('')+'</select><input id="amt" type="number" min="1" placeholder="Betrag €"><input id="note" maxlength="120" placeholder="Verwendungszweck"><button id="send">ÜBERWEISEN</button><h3>Kontoauszug</h3>'+trs.map(t=>'<div class="row">'+Number(t.amount).toLocaleString('de-DE')+' € · '+esc(t.purpose||'Überweisung')+'</div>').join('')+(profile.is_admin?'<hr><h3>Geld verschenken</h3><select id="ato">'+ps.map(x=>'<option value="'+x.id+'">'+esc(x.player_name)+'</option>').join('')+'</select><input id="aamt" type="number" value="100000"><button id="grant">GELD SCHENKEN</button>':''));
$('#send').onclick=async()=>{let {error}=await sb.rpc('transfer_money',{to_user:$('#to').value,amt:+$('#amt').value,note:$('#note').value});alert(error?error.message:'Überweisung ausgeführt.');if(!error)location.reload()};if($('#grant'))$('#grant').onclick=async()=>{let {error}=await sb.rpc('admin_grant_money',{to_user:$('#ato').value,amt:+$('#aamt').value});alert(error?error.message:'Geld überwiesen.');if(!error)location.reload()}}
async function homesUI(){if(!session)return authUI();let hs=(await sb.from('homes').select('*').order('id')).data||[];modal('<h2>🏠 Wohnen</h2><p>60 Wohnmöglichkeiten. Der erste Spielmonat ist als Startwohnung vorgesehen.</p>'+hs.map(h=>'<div class="row"><b>'+esc(h.label)+'</b> · '+(h.kind==='wohnung'?'Wohnung':'Haus')+'<br>Miete '+Number(h.rent).toLocaleString('de-DE')+' €/Monat · Kauf '+Number(h.buy_price).toLocaleString('de-DE')+' €<br>'+(h.owner||h.tenant?'Belegt':'Frei')+'</div>').join(''))}
await load();sb.auth.onAuthStateChange(async(e)=>{if(e==='PASSWORD_RECOVERY'){let p=prompt('Neues Passwort (mindestens 8 Zeichen)');if(p){let {error}=await sb.auth.updateUser({password:p});alert(error?error.message:'Passwort geändert.')}}});
async function startup(){
 const login=$('#login'),hud=$('#hud'),st=$('#loginStatus'),email=$('#email'),pass=$('#pass'),pn=$('#playerName');
 const show=()=>{login.hidden=false;hud.hidden=true}, enter=async()=>{await load();if(!session)return show();login.hidden=true;hud.hidden=false;$('#who').textContent=profile?.player_name||session.user.email;$('#money').textContent=Number(profile?.cash||0).toLocaleString('de-DE')+' €';if(profile?.is_admin&&!$('#testAdmin')){let b=document.createElement('button');b.id='testAdmin';b.textContent='TEST';b.onclick=bankUI;hud.appendChild(b)}};
 if(!session)show();else await enter();
 $('#go').onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:pass.value});st.textContent=error?error.message:'';if(!error)await enter()};
 $('#register').onclick=async()=>{let {error}=await sb.auth.signUp({email:email.value.trim(),password:pass.value,options:{data:{player_name:pn.value.trim()||'Spieler'}}});st.textContent=error?error.message:'Konto erstellt. Bitte E-Mail bestätigen.'};
 $('#forgot').onclick=async()=>{let {error}=await sb.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:location.origin+location.pathname});st.textContent=error?error.message:'E-Mail zum Zurücksetzen wurde gesendet.'};
 $('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
}
await startup();
let h=$('#hud');if(h){for(let [txt,fn] of [['KONTO',authUI],['ÜBERWEISEN',bankUI],['WOHNEN',homesUI]]){let b=document.createElement('button');b.textContent=txt;b.onclick=fn;h.appendChild(b)}}
window.LuxAccounts={open:authUI,bank:bankUI,homes:homesUI,get profile(){return profile},canCredit(){return(profile?.employment_months||0)>=6}};
