(()=>{let timer=setInterval(()=>{if(!window.LuxWorld)return;clearInterval(timer);const W=LuxWorld,AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;
let ctx=null,master=null,unlocked=false,noise=null,last={x:W.player.position.x,z:W.player.position.z},stepClock=0,lastSpeed=0,lastDriving=false,prev=new WeakMap(),voices=[];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function init(){if(ctx)return;ctx=new AC();master=ctx.createGain();let saved=Number(localStorage.getItem('lux_audio_volume'));let vol=Number.isFinite(saved)?Math.min(saved,.34):.28;master.gain.value=vol;localStorage.setItem('lux_audio_volume',String(vol));master.connect(ctx.destination);noise=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);let a=noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;voices=[makeVoice(),makeVoice()]}
function unlock(){init();if(ctx.state==='suspended')ctx.resume();unlocked=true}
for(let e of ['pointerdown','touchstart','keydown'])addEventListener(e,unlock,{passive:true});
function panNode(){return ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain()}
function relPan(v){let dx=v.position.x-W.player.position.x,dz=v.position.z-W.player.position.z,a=Math.atan2(dx,dz)-W.yaw;return clamp(Math.sin(a),-1,1)}
function burst(gain=.018,dur=.07,freq=850,type='noise',pan=0,low=1800){if(!unlocked||!ctx)return;let n=ctx.currentTime,g=ctx.createGain(),f=ctx.createBiquadFilter(),p=panNode();if(p.pan)p.pan.setValueAtTime(pan,n);f.type='lowpass';f.frequency.value=low;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),n+.006);g.gain.exponentialRampToValueAtTime(.0001,n+dur);g.connect(f);f.connect(p);p.connect(master);if(type==='noise'){let s=ctx.createBufferSource();s.buffer=noise;s.connect(g);s.start(n);s.stop(n+dur+.03)}else{let o=ctx.createOscillator();o.type=type;o.frequency.value=freq;o.connect(g);o.start(n);o.stop(n+dur+.03)}}
function loopOsc(type,freq){let o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=type;o.frequency.value=freq;g.gain.value=.0001;f.type='lowpass';f.frequency.value=1500;o.connect(f);f.connect(g);g.connect(master);o.start();return{o,g,f}}
function noiseLoop(freq){let s=ctx.createBufferSource(),g=ctx.createGain(),f=ctx.createBiquadFilter();s.buffer=noise;s.loop=true;g.gain.value=.0001;f.type='bandpass';f.frequency.value=freq;s.connect(f);f.connect(g);g.connect(master);s.start();return{s,g,f}}
function makeVoice(){let o=ctx.createOscillator(),n=ctx.createBufferSource(),og=ctx.createGain(),ng=ctx.createGain(),f=ctx.createBiquadFilter(),p=panNode();o.type='sawtooth';o.frequency.value=75;n.buffer=noise;n.loop=true;og.gain.value=.0001;ng.gain.value=.0001;f.type='lowpass';f.frequency.value=800;o.connect(og);n.connect(ng);og.connect(f);ng.connect(f);f.connect(p);p.connect(master);o.start();n.start();return{o,og,ng,f,p}}
function foot(){let inside=!!(window.LuxInteriors530?.inside||window.LuxInteriors520?.inside),wet=(window.LuxWeather560||window.LuxWeather470)?.state==='rain';burst(inside?.018:wet?.022:.018,inside?.05:.07,inside?1200:700,'noise',0,inside?1800:1300)}
function door(open,id=''){let metal=['mill','sugar','bottler','post','police','fire','rescue','hospital'].includes(id);burst(metal?.021:.018,metal?.14:.1,metal?520:240,'noise',0,metal?1300:800);setTimeout(()=>burst(.011,.05,open?120:90,'triangle',0,600),90)}
function horn(source,kind='car'){if(!unlocked||!ctx)return;let dist=source?.position?Math.hypot(source.position.x-W.player.position.x,source.position.z-W.player.position.z):0,max=(kind==='truck'||kind==='bus')?28:22;if(dist>max)return;let att=Math.pow(1-dist/max,2),pan=source?.position?relPan(source):0,heavy=kind!=='car';burst((heavy?.032:.025)*att,heavy?.25:.18,heavy?280:410,'square',pan,heavy?1000:1400)}
function aiHorn(v){let u=v?.userData||{};horn(v,u.bus470?'bus':(u.delivery510||u.garbage510||u.emergency500)?'truck':'car')}
function warningBeep(source){let d=source?.position?Math.hypot(source.position.x-W.player.position.x,source.position.z-W.player.position.z):0;if(d>14)return;burst(.014*Math.pow(1-d/14,2),.07,980,'square',source?relPan(source):0,1500)}
function bell(){burst(.009,.5,392,'sine',0,1100);setTimeout(()=>burst(.006,.65,523,'sine',0,1200),120)}
init();let ev1=loopOsc('sine',115),ev2=loopOsc('triangle',225),tire=noiseLoop(620),rain=noiseLoop(2200),siren=loopOsc('sine',760),lastBus=false;
function updateTraffic(dt){let pc=window.LuxPlayerCar471||window.LuxPlayerCar400,x=W.player.position.x,z=W.player.position.z,c=[];for(let v of W.cars||[]){if(v===pc?.car||v.visible===false)continue;let p=prev.get(v)||{x:v.position.x,z:v.position.z},sp=Math.min(25,Math.hypot(v.position.x-p.x,v.position.z-p.z)/Math.max(dt,.001));prev.set(v,{x:v.position.x,z:v.position.z});let d=Math.hypot(v.position.x-x,v.position.z-z),heavy=!!(v.userData?.bus470||v.userData?.delivery510||v.userData?.garbage510||v.userData?.emergency500),max=heavy?20:14;if(d<max&&(sp>.12||heavy))c.push({v,sp,d,max,heavy})}c.sort((a,b)=>a.d-b.d);let now=ctx.currentTime;for(let i=0;i<voices.length;i++){let vc=voices[i],a=c[i];if(!a){vc.og.gain.setTargetAtTime(.0001,now,.15);vc.ng.gain.setTargetAtTime(.0001,now,.15);continue}let att=Math.pow(1-a.d/a.max,2),inside=!!window.LuxInteriors530?.inside;if(inside)att*=.18;vc.o.frequency.setTargetAtTime((a.heavy?58:82)+a.sp*(a.heavy?4:6),now,.1);vc.f.frequency.setTargetAtTime(inside?350:(a.heavy?650:900),now,.1);vc.og.gain.setTargetAtTime(Math.max(.0001,(a.heavy?.009:.006)*att),now,.12);vc.ng.gain.setTargetAtTime(Math.max(.0001,(a.heavy?.008:.005)*att),now,.12);if(vc.p.pan)vc.p.pan.setTargetAtTime(relPan(a.v),now,.1)}}
W.registerTick(dt=>{if(!unlocked||!ctx)return;let now=ctx.currentTime,pc=window.LuxPlayerCar471||window.LuxPlayerCar400,driving=!!pc?.driving,sp=Math.abs(pc?.speed||0),x=W.player.position.x,z=W.player.position.z,d=Math.hypot(x-last.x,z-last.z),walk=d/Math.max(dt,.001);last={x,z};if(driving!==lastDriving){lastDriving=driving;burst(.018,.08,driving?180:130,'noise',0,700)}if(!driving&&walk>.3&&d<2.5){stepClock+=dt;if(stepClock>.43){stepClock=0;foot()}}else stepClock=0;let acc=(sp-lastSpeed)/Math.max(dt,.001);lastSpeed=sp;let own=driving&&sp>.1?Math.min(.023,.004+sp*.00075+Math.max(0,acc)*.00025):.0001;ev1.o.frequency.setTargetAtTime(105+sp*15,now,.08);ev2.o.frequency.setTargetAtTime(210+sp*24,now,.08);ev1.g.gain.setTargetAtTime(own,now,.1);ev2.g.gain.setTargetAtTime(own*.22,now,.1);tire.f.frequency.setTargetAtTime(480+sp*16,now,.1);tire.g.gain.setTargetAtTime(driving&&sp>1?Math.min(.025,sp*.0009):.0001,now,.1);updateTraffic(dt);let wet=(window.LuxWeather560||window.LuxWeather470)?.state==='rain',inside=!!window.LuxInteriors530?.inside;rain.g.gain.setTargetAtTime(wet?(inside?.004:.013):.0001,now,.3);let ef=window.LuxEmergency500?.fleet||{},best=null,bd=999;for(let f of Object.values(ef)){if(f.state==='base'||f.v?.visible===false)continue;let dd=Math.hypot(f.v.position.x-x,f.v.position.z-z);if(dd<bd){bd=dd;best=f}}let sg=best&&bd<38?Math.pow(1-bd/38,2)*.025:.0001;if(inside)sg*=.18;siren.o.frequency.setTargetAtTime((Date.now()/650)%2<1?700:930,now,.05);siren.g.gain.setTargetAtTime(Math.max(.0001,sg),now,.12);let bus=window.LuxCityActivity560?.bus||window.LuxCityActivity530?.bus,bo=!!bus?.userData?.busStopOpen;if(bo!==lastBus){lastBus=bo;if(bus&&Math.hypot(bus.position.x-x,bus.position.z-z)<14)door(bo,'bus')}});
function setVolume(v){let n=clamp(+v||0,0,.5);master.gain.value=n;localStorage.setItem('lux_audio_volume',String(n))}
let api={unlock,door,horn,aiHorn,warningBeep,bell,get active(){return unlocked},setVolume};window.LuxAudio520=window.LuxAudio530=window.LuxAudio540=window.LuxAudio550=window.LuxAudio560=api;
},220)})();