(()=>{const K="luxcity_bakery_v380";let S;try{S=JSON.parse(localStorage.getItem(K)||"{}")}catch{S={}};Object.assign(S,{customers:S.customers||0,lost:S.lost||0,lastCustomer:S.lastCustomer||0,machines:S.machines||{ofen:1,kneter:1,gaerung:1},display:S.display||{},productionLog:S.productionLog||[]});const save=()=>localStorage.setItem(K,JSON.stringify(S)),G=()=>window.LuxGameplay?.state,B=()=>window.LuxBusinessRisk?.state,L=()=>window.LuxLife?.state;
const recipes={baguette:{label:"Baguette tradition",out:10,mins:45,use:{mehl:5,wasser:3},price:2.2},brot:{label:"Pain de campagne",out:8,mins:70,use:{mehl:6,wasser:3},price:3.8},croissant:{label:"Croissant au beurre",out:12,mins:90,use:{mehl:4,zucker:1,milch:2},price:1.9},painchoco:{label:"Pain au chocolat",out:12,mins:95,use:{mehl:4,zucker:1,milch:2},price:2.1},kaiser:{label:"Kaisersemmel",out:18,mins:55,use:{mehl:5,wasser:3},price:.85},quetsch:{label:"Quetschentaart",out:8,mins:80,use:{mehl:3,zucker:2,milch:1},price:3.2}};
function active(){return B()?.status!=="bankrupt"}
function bakeryStaff(){return (L()?.employees||[]).filter(e=>["Bäcker","Verkäufer","Reinigung"].includes(e.job))}
function produce(id,batches=1){let g=G(),r=recipes[id];batches=Math.max(1,Math.min(100,+batches||1));if(!active())return alert("Firma ist insolvent. Keine Produktion möglich.");if(!g||!r)return;for(let k in r.use)if((g.inventory[k]||0)<r.use[k]*batches)return alert("Nicht genug "+k+" für "+batches+" Chargen.");for(let k in r.use)g.inventory[k]-=r.use[k]*batches;let bakers=bakeryStaff().filter(e=>e.job==="Bäcker").length,speed=1+Math.min(2,bakers*.12)+(S.machines.ofen-1)*.08;g.production.push({id,ready:Date.now()+r.mins*1000/speed,v380:true,out:r.out*batches,label:r.label});S.productionLog.unshift({label:r.label,batches,time:Date.now()});S.productionLog=S.productionLog.slice(0,20);G().save?.();save();ui()}
function customer(){let g=G();if(!g||!active())return;let sellers=bakeryStaff().filter(e=>e.job==="Verkäufer").length,ids=Object.keys(recipes).filter(id=>(g.products[id]||0)>0);if(!ids.length){S.lost++;save();return}let id=ids[Math.floor(Math.random()*ids.length)],r=recipes[id],qty=Math.min(g.products[id]||0,1+Math.floor(Math.random()*4));if(!qty){S.lost++;return}g.products[id]-=qty;let rev=qty*r.price*(1+Math.min(.15,sellers*.015));B()?.revenue?.(rev);g.dayRevenue=(g.dayRevenue||0)+rev;S.customers++;S.lastCustomer=Date.now();g.save?.();save()}
function completeProduction(){let g=G();if(!g)return;let now=Date.now(),changed=false;g.production=g.production.filter(p=>{if(p.v380&&p.ready<=now){g.products[p.id]=(g.products[p.id]||0)+(p.out||recipes[p.id]?.out||0);changed=true;return false}return true});if(changed)g.save?.()}
function ui(){let m=document.getElementById("modal"),b=document.getElementById("modalBody"),g=G(),br=B();if(!m||!b||!g)return;m.hidden=false;let inv=Object.entries(g.inventory).map(([k,v])=>k+": "+Math.round(v*100)/100).join(" · "),prod=Object.entries({...g.products,painchoco:g.products.painchoco||0,kaiser:g.products.kaiser||0,quetsch:g.products.quetsch||0}).map(([k,v])=>k+": "+v).join(" · ");b.innerHTML="<h2>🥖 Bäckerei – Backstube & Verkauf</h2><p><b>Firmenkonto:</b> "+Math.round(br?.businessCash||0).toLocaleString("de-DE")+" € · <b>Mitarbeiter:</b> "+bakeryStaff().length+" · <b>Kunden:</b> "+S.customers+" · verloren wegen leerer Theke: "+S.lost+"</p><h3>Lager – unbegrenzte Kapazität</h3><p>"+inv+"</p><button id='sup380'>WARE BESTELLEN / LIEFERANTEN</button> <button id='inv380'>RECHNUNGEN</button><h3>Backstube</h3><p>Öfen "+S.machines.ofen+" · Kneter "+S.machines.kneter+" · Gärung "+S.machines.gaerung+"</p>"+Object.entries(recipes).map(([id,r])=>"<div><b>"+r.label+"</b> · "+r.out+" Stück/Charge · "+r.mins+" Min. <input data-q='"+id+"' type='number' min='1' max='100' value='1' style='width:65px'><button data-p='"+id+"'>PRODUZIEREN</button></div>").join("")+"<p>Laufende Produktion: "+g.production.length+"</p><h3>Verkaufstheke</h3><p>"+prod+"</p><h3>Personal</h3><p>"+bakeryStaff().map(e=>e.name+" – "+e.job).join(" · ")||"Noch kein Bäckerei-Personal eingestellt.")+"</p><button id='staff380'>PERSONAL VERWALTEN</button>";b.querySelectorAll("[data-p]").forEach(x=>x.onclick=()=>produce(x.dataset.p,+b.querySelector("[data-q='"+x.dataset.p+"']").value));b.querySelector("#inv380").onclick=()=>LuxSupplier360?.ui?.();b.querySelector("#sup380").onclick=()=>{window.LuxGameplay?.open?.()};b.querySelector("#staff380").onclick=()=>document.getElementById("staffBtn")?.click()}
function nearBakery(){let w=window.LuxWorld,d=window.LuxCityServices?.buildings?.find(x=>x.id==="bakery");return !!(w&&d&&Math.hypot(w.player.position.x-d.x,w.player.position.z-(d.z+d.l/2))<18)}
let hud=setInterval(()=>{let h=document.getElementById("hud");if(h&&!document.getElementById("bakery380")){let b=document.createElement("button");b.id="bakery380";b.textContent="BÄCKEREI";b.onclick=()=>nearBakery()?ui():alert("Geh zuerst zur Bäckerei.");h.appendChild(b);clearInterval(hud)}},500);
setInterval(()=>{completeProduction();let l=L(),hour=l?.hour??12;if(hour>=6&&hour<19){let staff=bakeryStaff(),rate=staff.some(e=>e.job==="Verkäufer")?0.32:0.12;if(Math.random()<rate)customer()}},2500);window.LuxBakery380={state:S,recipes,produce,customer,ui,save}})();