// Lux City v0.9.3 bakery management + visible delivery yard
export function installBakeryV093(T,S,mesh,bp,getState,save,hud,show){
 const mark=(x,z)=>{let p=mesh(new T.BoxGeometry(4.8,.05,8),0x55595b,x,.08,z);for(let q of[-1,1])mesh(new T.BoxGeometry(.12,.06,7.2),0xf5f5f0,x+q*2.2,.12,z);return p};
 mark(bp.x-6,bp.z+16);mark(bp.x+6,bp.z+16);
 for(let x of[bp.x-6,bp.x+6]){let g=new T.Group();mesh(new T.BoxGeometry(3.2,1.8,5.6),0xf2f2f2,0,1,0,0,g);mesh(new T.BoxGeometry(2.7,.85,2.1),0xd9edf4,0,2,-.65,0,g);mesh(new T.BoxGeometry(2.4,.45,.08),0xe4b93f,0,1.25,2.85,0,g);g.position.set(x,.1,bp.z+16);S.add(g)}
 let st=getState();st.inventory??={Farine_T55:50,Beurre:10,Sucre:20,Sel:10,Levure:3,Lait:12,Oeufs:120};st.staff??=[];st.finished??={};st.prices??={'Baguette tradition':2.2,'Croissant au beurre':1.75,'Pain au chocolat':1.95,'Pain au levain':5.2};
 const products=[['Baguette tradition','2 h 45 min'],['Pain au levain','15 h'],['Petit pain','2 h 30 min'],['Croissant au beurre','12 h'],['Pain au chocolat','12 h'],['Brioche','3 h 30 min'],['Quetschentaart','2 h 15 min'],['Boxemännchen','1 h 25 min'],['Bretzel luxembourgeoise','10 h'],['Verwurelter','2 h'],['Bamkuch','5 h'],['Rieslingspaschtéit','4 h'],['Quiche lorraine','1 h 45 min'],['Sandwich jambon-fromage','20 min']];
 function nav(){return '<div class="tabs"><button data-tab="prod">🥖 Backen</button><button data-tab="stock">📦 Lager</button><button data-tab="staff">👥 Angestellte</button><button data-tab="price">💶 Preise</button></div>'}
 function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>open(b.dataset.tab))}
 function open(tab='prod'){st=getState();let h='<h2>🥖 Bäckerei-Verwaltung</h2>'+nav();if(tab==='prod')h+='<h3>Produktion</h3>'+products.map((p,i)=>'<div class="row"><b>'+p[0]+'</b><br>Produktionszeit: '+p[1]+'<br><button data-bake="'+i+'">Produktion starten</button></div>').join('');if(tab==='stock')h+='<h3>Lager & Bestellungen</h3>'+Object.entries(st.inventory||{}).map(x=>'<div class="row"><b>'+x[0].replaceAll('_',' ')+'</b>: '+x[1]+'</div>').join('')+'<div class="row"><button id="orderFlour">25 kg Mehl bestellen · 23,90 €</button></div>';if(tab==='staff')h+='<h3>Angestellte</h3><div class="row">Aktuell: '+(st.staff?.length||0)+' Mitarbeiter</div><div class="row"><button id="hireBaker">Bäcker einstellen · 3.250 €/Monat</button></div><div class="row"><button id="hireSales">Verkäufer einstellen · 2.850 €/Monat</button></div>';if(tab==='price')h+='<h3>Verkaufspreise</h3>'+Object.entries(st.prices||{}).map(([n,p],i)=>'<div class="row"><b>'+n+'</b><br><input data-price="'+n+'" type="number" step=".05" min=".1" value="'+p+'"> €</div>').join('')+'<button id="savePrices">Preise speichern</button>';show(h);bind();document.querySelectorAll('[data-bake]').forEach(b=>b.onclick=()=>{let p=products[+b.dataset.bake][0];st.finished[p]=(st.finished[p]||0)+10;save();alert('10 × '+p+' wurden zur Produktion eingeplant.')});let of=document.querySelector('#orderFlour');if(of)of.onclick=()=>{if(st.cash<23.9)return alert('Nicht genug Geld');st.cash-=23.9;st.inventory.Farine_T55=(st.inventory.Farine_T55||0)+25;save();hud();open('stock')};let hb=document.querySelector('#hireBaker');if(hb)hb.onclick=()=>{st.staff.push({role:'Bäcker',salary:3250});save();open('staff')};let hs=document.querySelector('#hireSales');if(hs)hs.onclick=()=>{st.staff.push({role:'Verkäufer',salary:2850});save();open('staff')};let sp=document.querySelector('#savePrices');if(sp)sp.onclick=()=>{document.querySelectorAll('[data-price]').forEach(i=>st.prices[i.dataset.price]=Math.max(.1,+i.value||.1));save();alert('Preise gespeichert.')}}return open}