// v4.4.3 commercial ownership authority
export const ECON={properties:{bakery:{buy:620000,rent:4200},cafe:{buy:540000,rent:3600},pub:{buy:690000,rent:4800},mill:{buy:1350000,rent:8500},sugar:{buy:980000,rent:6900},bottler:{buy:1850000,rent:11500},post:{buy:1450000,rent:9200}},nodes:{farm:{name:'Getreidehof',ai:true,produces:['Weizen','Roggen']},mill:{name:'Mühle',ai:true,needs:['Weizen','Roggen'],produces:['Mehl T55','Roggenmehl']},sugar:{name:'Zuckerbetrieb',ai:true,produces:['Zucker']},bottler:{name:'Getränke-Abfüller',ai:true,produces:['Wasser','Cola','Saft','Bier','Wein']},post:{name:'Lux City Post & Logistik',ai:true,service:['Pakete','Warenlieferung']},bakery:{name:'Bäckerei',ai:true,needs:['Mehl T55','Roggenmehl','Zucker']},cafe:{name:'Café',ai:true,needs:['Kaffeebohnen','Milch','Zucker','Gebäck']},pub:{name:'Kneipe',ai:true,needs:['Wasser','Cola','Saft','Bier','Wein']}}};
const K='luxcity_economy_v097';
export function currentPlayer(){let a=window.LuxAccount;return{id:a?.session?.user?.id||localStorage.getItem('luxcity_player_id')||'local',name:a?.profile?.player_name||document.querySelector('#who')?.textContent?.replace('👤','').trim()||'Spieler'}}
export function loadEconomy(){let s;try{s=JSON.parse(localStorage.getItem(K)||'{}')}catch{s={}}s.owners??={};s.orders??=[];s.ai??={};let me=currentPlayer();for(let [id,o] of Object.entries(s.owners)){if(o&&!o.userId&&o.player&&(o.player===me.name||!o.player.includes('-'))){o.userId=me.id;o.player=o.player||me.name}}for(const id of Object.keys(ECON.nodes))s.ai[id]=!s.owners[id];localStorage.setItem(K,JSON.stringify(s));return s}
export function ownerOf(id){return loadEconomy().owners?.[id]||null}
export function isMine(id){let o=ownerOf(id),me=currentPlayer();return !!o&&(o.userId===me.id||(!o.userId&&o.player===me.name))}
export function claimBusiness(id,mode){let s=loadEconomy(),p=ECON.properties[id],me=currentPlayer();if(!p)return{ok:false,reason:'Betrieb unbekannt.'};let old=s.owners[id];if(old){if(old.userId===me.id||(!old.userId&&old.player===me.name))return{ok:false,reason:'Dieser Betrieb gehört dir bereits.'};return{ok:false,reason:'Dieser Betrieb wird bereits von '+(old.player||'einem anderen Spieler')+' geführt.'}}if(!['buy','rent'].includes(mode))return{ok:false,reason:'Ungültige Übernahmeart.'};s.owners[id]={userId:me.id,player:me.name,mode,since:Date.now(),monthlyRent:mode==='rent'?(p.rent||0):0};s.ai[id]=false;localStorage.setItem(K,JSON.stringify(s));return{ok:true,owner:s.owners[id]}}
export function releaseBusiness(id,force=false){let s=loadEconomy();if(!force&&!isMine(id))return false;delete s.owners[id];s.ai[id]=true;localStorage.setItem(K,JSON.stringify(s));return true}
export function myBusinesses(){let s=loadEconomy();return Object.keys(s.owners||{}).filter(isMine)}
export function routeOrder(from,to,item,qty=1){let s=loadEconomy();let carrier=s.owners.post?'player-post':'ai-post';let o={id:Date.now()+'-'+Math.random(),from,to,item,qty,carrier,status:'ordered',created:Date.now(),eta:Date.now()+86400000};s.orders.push(o);localStorage.setItem(K,JSON.stringify(s));return o}
window.LuxEconomy={ECON,loadEconomy,currentPlayer,ownerOf,isMine,claimBusiness,releaseBusiness,myBusinesses,routeOrder};loadEconomy();