(()=>{const wait=setInterval(()=>{if(!window.LuxWorld)return;clearInterval(wait);init()},150);function init(){const W=LuxWorld,T=W.THREE,p=W.player,user=()=>((document.querySelector('#who')?.textContent||document.querySelector('#user')?.value||'spieler').replace('👤','').trim()||'spieler'),K=()=> 'luxcity_foundation_v170_'+user(),read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));window.LuxFoundation=window.LuxFoundation||{};let save=read(K());if(save.player){p.position.x=save.player.x??p.position.x;p.position.z=save.player.z??p.position.z;W.yaw=save.player.yaw??W.yaw}
const av=window.LuxAvatar||read('luxcity_avatar_'+user());if(av){let meshes=[];p.traverse(x=>{if(x.isMesh&&x.material?.color)meshes.push(x)});meshes.forEach((m,i)=>{let c=i===0?av.pants:i===1?av.shirt:(i===2?av.skin:null);if(c)m.material.color.set(c)})}
let car=null,driving=false,speed=0,keys={};function makeCar(){let V=window.LuxVehicles?.state,o=V?.owned||[];if(!o.length)return;let chosen=o.find(x=>x.id===V.active)||o[0];car=new T.Group;let body=new T.Mesh(new T.BoxGeometry(chosen.type==='van'?2.05:chosen.type==='suv'?1.95:1.82,chosen.type==='van'?1.25:chosen.type==='suv'?1.05:.82,chosen.type==='van'?5.15:chosen.type==='suv'?4.75:4.45),new T.MeshStandardMaterial({color:0x3d526b}));body.position.y=chosen.type==='van'?1.0:chosen.type==='suv'?.82:.72;car.add(body);let cab=new T.Mesh(new T.BoxGeometry(chosen.type==='van'?1.88:chosen.type==='suv'?1.7:1.58,chosen.type==='van'?.9:.7,chosen.type==='van'?2.35:2.05),new T.MeshStandardMaterial({color:0x7890a0}));cab.position.set(0,chosen.type==='van'?1.72:chosen.type==='suv'?1.48:1.34,chosen.type==='van'?.25:-.25);car.add(cab);car.position.set(p.position.x+3,0,p.position.z+2);if(save.vehicle){car.position.set(save.vehicle.x,0,save.vehicle.z);car.rotation.y=save.vehicle.rot||0}W.scene.add(car)}
makeCar();function toggle(){if(!car)return;let d=Math.hypot(p.position.x-car.position.x,p.position.z-car.position.z);if(!driving&&d<4){driving=true;p.visible=false}else if(driving){driving=false;p.visible=true;p.position.set(car.position.x+2,0,car.position.z)}}addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='e'&&!e.repeat)toggle()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
W.registerTick((dt)=>{if(!driving||!car)return;let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0);speed+=(f*10-speed*2.8)*dt;speed=Math.max(-6,Math.min(14,speed));let steer=(keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0);if(Math.abs(speed)>.15)car.rotation.y+=steer*1.6*dt*Math.sign(speed);let nx=car.position.x+Math.sin(car.rotation.y)*speed*dt,nz=car.position.z+Math.cos(car.rotation.y)*speed*dt;if(!W.hit(nx,nz)){car.position.x=nx;car.position.z=nz}else speed=0;p.position.x=car.position.x;p.position.z=car.position.z;W.yaw=car.rotation.y});
let hud=document.getElementById('hud');if(hud){let b=document.createElement('button');b.textContent='AUTO EIN/AUS';b.onclick=toggle;hud.appendChild(b)}
function staff(){let e=window.LuxLife?.state?.employees||[],m={production:1,sales:1,logistics:1};for(let x of e){if(x.job==='Bäcker')m.production+=.12;if(x.job==='Verkäufer')m.sales+=.1;if(x.job==='Fahrer'||x.job==='Lagerist')m.logistics+=.12}LuxFoundation.staffMultipliers=m}staff();setInterval(staff,3000);
setInterval(()=>{let sh=window.LuxSupply?.state?.shipments||[],inv=window.LuxGameplay?.state?.inventory;if(!inv)return;for(let x of sh){if(x.foundationApplied)continue;if((x.status==='completed'||x.status==='delivered'||(x.eta&&x.eta<=Date.now()))&&x.item){let map={'Mehl T55':'mehl','Zucker':'zucker','Wasser':'wasser','Milch':'milch','Kaffeebohnen':'kaffee'},k=map[x.item]||String(x.item).toLowerCase();if(k in inv){inv[k]+=(+x.qty||0);x.foundationApplied=true;window.LuxGameplay?.save?.();window.LuxSupply?.save?.()}}}},1000);
let last=save.lastFinanceMonth||'';setInterval(()=>{if(window.LuxCore390)return;let L=window.LuxLife?.state,G=window.LuxGameplay?.state;if(!L||!G)return;let ym=L.year+'-'+L.month;if(!last){last=ym;return}if(ym===last)return;last=ym;save.lastFinanceMonth=last;write(K(),save);let rent=+G.rent||0,bk='lux9_'+user(),bs=read(bk),bp=+bs.activeLoan?.payment||0,gp=+G.loanPayment||0,loan=Math.max(bp,gp);if(rent+loan>0)window.LuxLife?.addExpense?.(rent+loan);if(bp&&bs.activeLoan){bs.activeLoan.remaining=Math.max(0,(+bs.activeLoan.remaining||0)-bp);bs.debt=bs.activeLoan.remaining;if(!bs.debt)bs.activeLoan=null;write(bk,bs)}},1000);
function persist(){save.player={x:p.position.x,z:p.position.z,yaw:W.yaw};save.vehicle=car?{x:car.position.x,z:car.position.z,rot:car.rotation.y}:null;save.lastFinanceMonth=last||save.lastFinanceMonth;write(K(),save)}setInterval(persist,5000);addEventListener('pagehide',persist)}})();