(()=>{const K='luxcity_gameplay_v630';let old={};try{old=JSON.parse(localStorage.getItem(K)||'{}')}catch{};let S={needs:Object.assign({hunger:100,durst:100,energie:100,hygiene:100},old.needs||{}),wellness:old.wellness||100,lastGameMinute:old.lastGameMinute??null,warnings:old.warnings||{}};const clamp=v=>Math.max(0,Math.min(100,v)),save=()=>localStorage.setItem(K,JSON.stringify(S));let lastNotice=0;
function totalMinute(){let L=window.LuxLife?.state;if(!L)return null;return((((L.year||2026)*12+(L.month||1))*30+(L.day||1))*24+(L.hour||0))*60+(L.minute||0)}
function status(){let n=S.needs,min=Math.min(n.hunger,n.durst,n.energie,n.hygiene);if(min<15)return'Kritisch';if(min<35)return'Erschöpft';if(min<60)return'Angeschlagen';return'Gut'}
function recompute(){let n=S.needs;S.wellness=Math.round((n.hunger+n.durst+n.energie+n.hygiene)/4)}
function hud(){let e=document.getElementById('simHud');if(!e){e=document.createElement('div');e.id='simHud';e.style='position:fixed;left:10px;bottom:10px;z-index:19;background:#0e151bdc;color:white;padding:8px 10px;border:1px solid #ffffff22;border-radius:10px;font:12px Arial;pointer-events:auto;backdrop-filter:blur(6px)';e.onclick=open;document.body.appendChild(e)}let n=S.needs;e.innerHTML='❤️ '+status()+' · '+S.wellness+'%<br>🍴 '+Math.round(n.hunger)+'  🥤 '+Math.round(n.durst)+'  ⚡ '+Math.round(n.energie)+'  🚿 '+Math.round(n.hygiene)}
function warn(){let n=S.needs,now=Date.now();if(now-lastNotice<15000)return;let msg=n.durst<20?'Du bist sehr durstig.':n.hunger<20?'Du solltest etwas essen.':n.energie<20?'Du brauchst Schlaf.':n.hygiene<20?'Du solltest duschen.':null;if(msg){lastNotice=now;let b=document.getElementById('needsWarn630');if(!b){b=document.createElement('div');b.id='needsWarn630';b.style='position:fixed;left:50%;bottom:86px;transform:translateX(-50%);z-index:24;background:#181d22e8;color:#fff;padding:9px 13px;border-radius:9px;border:1px solid #ffffff28;font:13px Arial;pointer-events:none';document.body.appendChild(b)}b.textContent=msg;b.style.display='block';setTimeout(()=>b.style.display='none',3500)}}
function advance(){let tm=totalMinute();if(tm==null)return;if(S.lastGameMinute==null){S.lastGameMinute=tm;save();return}let dm=Math.max(0,Math.min(180,tm-S.lastGameMinute));if(!dm)return;S.lastGameMinute=tm;let n=S.needs;n.hunger=clamp(n.hunger-dm*.065);n.durst=clamp(n.durst-dm*.085);n.energie=clamp(n.energie-dm*.043);n.hygiene=clamp(n.hygiene-dm*.022);recompute();warn();hud();save()}
function act(k,cost){if(cost){let cash=window.LuxLife?.state?.cash||0;if(cash<cost){alert('Nicht genug Privatgeld.');return false}LuxLife.addExpense(cost)}S.needs[k]=100;recompute();save();hud();return true}
function open(){let m=document.getElementById('modal'),b=document.getElementById('modalBody');if(!m||!b)return;m.hidden=false;m.style.display='block';let n=S.needs;b.innerHTML='<h2>❤️ Wohlbefinden</h2><p><b>'+status()+' · '+S.wellness+'%</b></p><p>Hunger '+Math.round(n.hunger)+' · Durst '+Math.round(n.durst)+' · Energie '+Math.round(n.energie)+' · Hygiene '+Math.round(n.hygiene)+'</p><p>Bedürfnisse verändern sich jetzt mit der <b>Spielzeit</b>, nicht mehr einfach jede echte Sekunde. Essen, Trinken, Schlafen und Duschen bleiben Teil deines Tagesablaufs.</p>'}
window.LuxGameplay=window.LuxGameplay630={state:S,open,save,act,status,advance};setInterval(advance,650);setTimeout(()=>{recompute();hud();advance()},900);addEventListener('beforeunload',save)})();