(()=>{const K='luxcity_gameplay_v630';let old={};try{old=JSON.parse(localStorage.getItem(K)||localStorage.getItem('luxcity_gameplay_v150')||'{}')}catch{};let S={needs:Object.assign({hunger:100,durst:100,energie:100,hygiene:100},old.needs||{}),wellness:old.wellness||100,lastGameMinute:old.lastGameMinute??null,warnings:old.warnings||{}};const clamp=v=>Math.max(0,Math.min(100,v)),save=()=>localStorage.setItem(K,JSON.stringify(S));let lastNotice=0;
function totalMinute(){let L=window.LuxLife?.state;if(!L)return null;return((((L.year||2026)*12+(L.month||1))*30+(L.day||1))*24+(L.hour||0))*60+(L.minute||0)}
function status(){let n=S.needs,min=Math.min(n.hunger,n.durst,n.energie,n.hygiene);if(min<15)return'Kritisch';if(min<35)return'Erschöpft';if(min<60)return'Angeschlagen';return'Gut'}
function recompute(){let n=S.needs;S.wellness=Math.round((n.hunger+n.durst+n.energie+n.hygiene)/4)}
function hudStyle(){if(document.getElementById('needsHud631Style'))return;let s=document.createElement('style');s.id='needsHud631Style';s.textContent=`
#simHud{position:fixed!important;left:50%!important;right:auto!important;top:8px!important;bottom:auto!important;transform:translateX(-50%)!important;z-index:17!important;background:#0a121bdc!important;color:#fff!important;padding:5px 7px!important;border:1px solid #ffffff20!important;border-radius:999px!important;font:11px Arial!important;pointer-events:auto!important;backdrop-filter:blur(8px);box-shadow:0 5px 18px #0006;display:flex!important;align-items:center!important;gap:4px!important;white-space:nowrap!important;max-width:min(430px,52vw)!important;overflow:hidden!important}
#simHud .needScore631{padding:3px 7px;border-radius:999px;background:#ffffff0d;font-weight:900}
#simHud .needChip631{display:inline-flex;align-items:center;gap:3px;padding:3px 5px;border-radius:999px;background:#ffffff0a;color:#e9eef2}
#simHud .needChip631.low{background:#7b241fcc;color:#ffe0da}
#simHud .needName631{font-size:9px;color:#aebbc5}
#needsWarn631{position:fixed!important;left:50%!important;top:48px!important;bottom:auto!important;transform:translateX(-50%)!important;z-index:24!important;background:#181d22e8!important;color:#fff!important;padding:7px 11px!important;border-radius:9px!important;border:1px solid #ffffff28!important;font:12px Arial!important;pointer-events:none!important;box-shadow:0 6px 20px #0007}
body:not(.game-ready) #simHud,body:not(.game-ready) #needsWarn631{display:none!important}
@media(max-width:900px) and (pointer:coarse){#simHud{top:7px!important;max-width:52vw!important;font-size:9px!important;padding:4px 5px!important;gap:2px!important}#simHud .needScore631{padding:3px 5px}#simHud .needChip631{padding:3px 4px}#simHud .needName631{display:none}#needsWarn631{top:43px!important;font-size:10px!important}}
@media(max-width:520px) and (orientation:portrait){#simHud{top:45px!important;max-width:70vw!important}}
`;document.head.appendChild(s)}
function hud(){hudStyle();let e=document.getElementById('simHud');if(!e){e=document.createElement('div');e.id='simHud';e.onclick=open;e.title='Wohlbefinden antippen für Details';document.body.appendChild(e)}let n=S.needs,chip=(icon,name,v)=>'<span class="needChip631 '+(v<25?'low':'')+'" title="'+name+'"><span>'+icon+'</span><span class="needName631">'+name+'</span><b>'+Math.round(v)+'</b></span>';e.innerHTML='<span class="needScore631">❤️ '+S.wellness+'%</span>'+chip('🍴','Essen',n.hunger)+chip('🥤','Trinken',n.durst)+chip('⚡','Energie',n.energie)+chip('🚿','Hygiene',n.hygiene)}
function warn(){let n=S.needs,now=Date.now();if(now-lastNotice<15000)return;let msg=n.durst<20?'Du bist sehr durstig.':n.hunger<20?'Du solltest etwas essen.':n.energie<20?'Du brauchst Schlaf.':n.hygiene<20?'Du solltest duschen.':null;if(msg){lastNotice=now;let b=document.getElementById('needsWarn631');if(!b){b=document.createElement('div');b.id='needsWarn631';document.body.appendChild(b)}b.textContent=msg;b.style.display='block';setTimeout(()=>b.style.display='none',3500)}}
function advance(){let tm=totalMinute();if(tm==null)return;if(S.lastGameMinute==null){S.lastGameMinute=tm;save();return}let dm=Math.max(0,Math.min(180,tm-S.lastGameMinute));if(!dm)return;S.lastGameMinute=tm;let n=S.needs;n.hunger=clamp(n.hunger-dm*.065);n.durst=clamp(n.durst-dm*.085);n.energie=clamp(n.energie-dm*.043);n.hygiene=clamp(n.hygiene-dm*.022);recompute();warn();hud();save()}
function act(k,cost){if(cost){let cash=window.LuxLife?.state?.cash||0;if(cash<cost){alert('Nicht genug Privatgeld.');return false}LuxLife.addExpense(cost)}S.needs[k]=100;recompute();save();hud();return true}
function open(){let m=document.getElementById('modal'),b=document.getElementById('modalBody');if(!m||!b)return;m.hidden=false;m.style.display='block';let n=S.needs;b.innerHTML='<h2>❤️ Wohlbefinden</h2><p><b>'+status()+' · '+S.wellness+'%</b></p><p>🍴 Essen '+Math.round(n.hunger)+' · 🥤 Trinken '+Math.round(n.durst)+' · ⚡ Energie '+Math.round(n.energie)+' · 🚿 Hygiene '+Math.round(n.hygiene)+'</p><p>Die Werte verändern sich mit der Spielzeit. Essen, Trinken, Schlafen und Duschen bleiben Teil deines Tagesablaufs.</p>'}
window.LuxGameplay=window.LuxGameplay630=window.LuxGameplay631=window.LuxGameplay632={state:S,open,save,act,status,advance,refreshHud:hud,recompute};setInterval(advance,650);setTimeout(()=>{recompute();hud();advance()},900);addEventListener('beforeunload',save)})();