import * as T from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
let q=setInterval(()=>{if(!window.LuxWorld||!window.LuxCityServices||!window.LuxSystems330)return;clearInterval(q);const W=LuxWorld,S=W.scene,D=LuxSystems330.doors,defs=LuxCityServices.buildings||[],extDoors=LuxCityServices.doorMeshes||{},M=(c,r=.65,m=.02)=>new T.MeshStandardMaterial({color:c,roughness:r,metalness:m}),A=(g,m,x,y,z,p=S)=>{let o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};
const names={bakery:'Bäckerei',cafe:'Café',pub:'Kneipe',mill:'Mühle',sugar:'Zuckerbetrieb',bottler:'Getränkeabfüllung',post:'Post & Logistik',police:'Polizei',fire:'Feuerwehr',rescue:'Rettungswache',hospital:'Krankenhaus',bank:'Lux City Bank',jobs:'Arbeitsamt',housing:'Wohnungsamt',townhall:'Gemeinde',colosseum:'Kolosseum'};
const ids=['bakery','cafe','pub','mill','sugar','bottler','post','police','fire','rescue','hospital','bank','jobs','housing','townhall','colosseum'],rooms={},groups={},doors={};let inside=null,returnPos=null,returnYaw=0;
for(let id of ids){if(extDoors[id]||!D[id])continue;let h=new T.Group();h.position.set(D[id].x-1,0,D[id].z+.05);let door=A(new T.BoxGeometry(2,3,.18),M(0x4b3428),1,1.5,0,h);S.add(h);extDoors[id]={hinge:h,door,open:false}}
function canvasSign(text){let c=document.createElement('canvas');c.width=640;c.height=100;let x=c.getContext('2d');x.fillStyle='#242424';x.fillRect(0,0,c.width,c.height);x.fillStyle='white';x.font='bold 38px Arial';x.textAlign='center';x.fillText(text,320,64);return new T.Mesh(new T.PlaneGeometry(8.5,1.35),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),side:T.DoubleSide}))}
function table(g,x,z,w=3,d=1.2,c=0x8b674a){A(new T.BoxGeometry(w,.16,d),M(c,.72),x,.83,z,g);for(let sx of[-1,1])for(let sz of[-1,1])A(new T.BoxGeometry(.16,.82,.16),M(0x504239),x+sx*(w/2-.18),.41,z+sz*(d/2-.18),g)}
function chair(g,x,z,rot=0){let a=A(new T.BoxGeometry(.7,.13,.7),M(0x5b4c41),x,.53,z,g);a.rotation.y=rot;A(new T.BoxGeometry(.7,.9,.12),M(0x5b4c41),x,.95,z-.29,g).rotation.y=rot}
function shelf(g,x,z,rot=0){let p=new T.Group();for(let y of[.35,1.15,1.95])A(new T.BoxGeometry(3,.12,.65),M(0x705845),0,y,0,p);for(let sx of[-1.42,1.42])A(new T.BoxGeometry(.12,2.2,.62),M(0x4c443e),sx,1.1,0,p);p.position.set(x,0,z);p.rotation.y=rot;g.add(p)}
function counter(g,x,z,w=6){A(new T.BoxGeometry(w,1.1,1.15),M(0x765741),x,.55,z,g);A(new T.BoxGeometry(w+.15,.12,1.35),M(0xb08d69,.5),x,1.15,z,g)}
function machine(g,x,z,c=0x6d7479,w=2,d=1.5,h=2){A(new T.BoxGeometry(w,h,d),M(c,.35,.35),x,h/2,z,g);A(new T.BoxGeometry(w*.72,.55,.06),M(0x1f2529,.15,.45),x,h*.62,z-d/2-.04,g)}
function bed(g,x,z){A(new T.BoxGeometry(3.8,.55,1.55),M(0xecece8),x,.55,z,g);A(new T.BoxGeometry(.5,1.4,1.65),M(0xd6d6d1),x-1.7,.75,z,g)}
function furnish(id,g,x,z){if(id==='bakery'){counter(g,x,z+4,7);shelf(g,x-7,z-4);machine(g,x+5,z-4,0x777b7d,2.4,2.1,2.2);machine(g,x+1,z-4,0x8b8f91,2,1.8,1.6);table(g,x,z,4,1.5)}else if(id==='cafe'||id==='pub'){counter(g,x,z-4,7);for(let p of[[-5,2],[0,2],[5,2],[-3,5],[3,5]]){table(g,x+p[0],z+p[1],2,1.2);chair(g,x+p[0]-1,z+p[1]+.2);chair(g,x+p[0]+1,z+p[1]-.2)}}else if(id==='bank'){counter(g,x,z-1,9);for(let xx of[-3,0,3]){A(new T.BoxGeometry(1.6,1.7,.8),M(0x3b4249,.35,.4),x+xx,.85,z-6,g);A(new T.BoxGeometry(.7,.5,.05),M(0x202a32,.1),x+xx,1.25,z-6.42,g)}A(new T.BoxGeometry(4,3.4,1.1),M(0x555b60,.3,.5),x+6,1.7,z-6,g)}else if(id==='police'){counter(g,x,z+3,6);for(let xx of[-5,0,5])table(g,x+xx,z-3,3,1.5);for(let xx of[-6.5,-5.7,-4.9])A(new T.BoxGeometry(.08,3.2,2.7),M(0x60676c,.3,.6),x+xx,1.6,z-6,g)}else if(id==='fire'||id==='rescue'){for(let xx of[-6,-2,2,6])A(new T.BoxGeometry(1.5,3,.8),M(id==='fire'?0xa9483e:0xd8d8d3,.45,.25),x+xx,1.5,z-6,g);table(g,x-4,z+2,4,1.5);table(g,x+3,z+2,4,1.5)}else if(id==='hospital'){counter(g,x,z+4,7);for(let xx of[-5,0,5])bed(g,x+xx,z-3)}else if(id==='post'){counter(g,x,z+3,7);for(let xx of[-6,-2,2,6])for(let zz of[-4,-7])A(new T.BoxGeometry(1.3,.9,1.1),M(0xb58f5d),x+xx,.45,z+zz,g)}else if(id==='mill'||id==='sugar'||id==='bottler'){for(let xx of[-6,-2,2,6])machine(g,x+xx,z-3,id==='mill'?0x8a8175:id==='sugar'?0xbfc0ba:0x7f9ea9,2.1,2.1,2.5);A(new T.BoxGeometry(15,.5,2),M(0x4c4f50,.4,.4),x,.35,z+4,g)}else if(id==='jobs'||id==='housing'||id==='townhall'){counter(g,x,z-2,8);for(let xx of[-5,-2,2,5])chair(g,x+xx,z+4);for(let xx of[-4,0,4])table(g,x+xx,z-6,3,1.3)}else if(id==='colosseum'){A(new T.CylinderGeometry(5,5,.3,32),M(0xb49368),x,.15,z,g);for(let a=0;a<Math.PI*2;a+=Math.PI/6){let seat=A(new T.BoxGeometry(2,.5,1),M(0x806d5a),x+Math.cos(a)*7,.35,z+Math.sin(a)*7,g);seat.rotation.y=-a+Math.PI/2}}}
function buildRoom(id,i){let x=-620+(i%4)*42,z=-260+Math.floor(i/4)*48,g=new T.Group(),wallColor=[0xd9c7b1,0xc7d3d4,0xd2c5b8,0xc9c9c3][i%4],w=28,d=24,h=6;A(new T.BoxGeometry(w,.2,d),M(0x82796d),0,.02,0,g);A(new T.BoxGeometry(w,.18,d),M(0xf1eee7,.9),0,h,0,g);A(new T.BoxGeometry(.35,h,d),M(wallColor),-w/2,h/2,0,g);A(new T.BoxGeometry(.35,h,d),M(wallColor),w/2,h/2,0,g);A(new T.BoxGeometry(w,h,.35),M(wallColor),0,h/2,-d/2,g);A(new T.BoxGeometry(11,h,.35),M(wallColor),-8.5,h/2,d/2,g);A(new T.BoxGeometry(11,h,.35),M(wallColor),8.5,h/2,d/2,g);let hinge=new T.Group();hinge.position.set(-1.25,0,d/2-.1);A(new T.BoxGeometry(2.5,3.2,.18),M(0x4b3428),1.25,1.6,0,hinge);g.add(hinge);doors[id]=hinge;for(let lx of[-7,0,7]){let l=new T.PointLight(0xfff2d4,1.15,16);l.position.set(lx,4.9,0);g.add(l);A(new T.BoxGeometry(2.2,.08,.5),new T.MeshStandardMaterial({color:0xfff1c7,emissive:0xffdf9a,emissiveIntensity:1}),lx,5.75,0,g)}let sg=canvasSign(names[id]||id);sg.position.set(0,4.7,-11.78);g.add(sg);furnish(id,g,0,0);g.position.set(x,0,z);S.add(g);groups[id]=g;for(let zz=-d/2;zz<=d/2;zz+=1.1){W.obstacles.push({x:x-w/2,z:z+zz,r:.62},{x:x+w/2,z:z+zz,r:.62})}for(let xx=-w/2;xx<=w/2;xx+=1.1)W.obstacles.push({x:x+xx,z:z-d/2,r:.62});for(let xx=-w/2;xx<=w/2;xx+=1.1)if(Math.abs(xx)>1.8)W.obstacles.push({x:x+xx,z:z+d/2,r:.62});rooms[id]={x,z,entry:{x,z:z+7},exit:{x,z:z+9.7},door:{x,z:z+11.4}}}
ids.forEach(buildRoom);
function nearDoor(id,max=4.2){let d=D[id],p=W.player;if(!d)return false;return Math.hypot(p.position.x-d.x,p.position.z-d.z)<=max}function animateDoor(id,open,external=true){let h=external?extDoors[id]?.hinge:doors[id];if(!h)return;let from=h.rotation.y,to=open?-Math.PI*.52:0,start=performance.now();function f(t){let k=Math.min(1,(t-start)/260),e=1-Math.pow(1-k,3);h.rotation.y=from+(to-from)*e;if(k<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function use(id){if(window.LuxPlayerCar400?.driving)return alert('Steig zuerst aus dem Auto.');if(inside){let r=rooms[inside];if(Math.hypot(W.player.position.x-r.exit.x,W.player.position.z-r.exit.z)>3.2)return alert('Geh direkt zur Ausgangstür.');let old=inside;animateDoor(old,true,false);setTimeout(()=>{W.player.position.set(returnPos.x,0,returnPos.z);W.yaw=returnYaw;inside=null;animateDoor(old,false,false);animateDoor(old,false,true)},180);return true}if(!id){for(let k of ids)if(nearDoor(k)){id=k;break}}if(!id||!rooms[id])return false;if(!nearDoor(id))return alert('Du bist zu weit weg. Geh direkt zur Tür.');returnPos={x:W.player.position.x,z:W.player.position.z};returnYaw=W.yaw;animateDoor(id,true,true);setTimeout(()=>{inside=id;let r=rooms[id];W.player.position.set(r.entry.x,0,r.entry.z);W.yaw=Math.PI;animateDoor(id,false,true)},240);return true}
let hint=null;function hints(){if(inside){if(!hint){hint=document.createElement('div');hint.id='insideHint441';hint.style='position:fixed;z-index:17;bottom:18px;left:50%;transform:translateX(-50%);background:#111c;color:white;padding:8px 12px;border-radius:8px';document.body.appendChild(hint)}hint.textContent='E = Gebäude verlassen';hint.style.display='block';return}let near=ids.find(k=>nearDoor(k,3.7));if(!near){if(hint)hint.style.display='none';return}if(!hint){hint=document.createElement('div');hint.id='insideHint441';hint.style='position:fixed;z-index:17;bottom:18px;left:50%;transform:translateX(-50%);background:#111c;color:white;padding:8px 12px;border-radius:8px';document.body.appendChild(hint)}hint.textContent='E = '+(names[near]||'Gebäude')+' betreten';hint.style.display='block'}setInterval(hints,180);
window.LuxCity402=window.LuxCity419=window.LuxInteriors441={rooms,use,nearDoor,get inside(){return inside}};if(window.LuxCity370)window.LuxCity370.useDoor=(...a)=>use(...a);addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&!e.repeat&&!window.LuxPlayerCar400?.driving)use()})},250);