import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s), canvas=$('#game'), renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa8c9d5);scene.fog=new THREE.FogExp2(0xa8c9d5,.004);const camera=new THREE.PerspectiveCamera(60,1,.1,800);
scene.add(new THREE.HemisphereLight(0xddeeff,0x596348,2.3));const sun=new THREE.DirectionalLight(0xfff4dd,3);sun.position.set(-70,100,40);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(700,700),new THREE.MeshStandardMaterial({color:0x708a54,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
function mesh(g,c,x,y,z){let m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:c,roughness:.78}));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
const road=mesh(new THREE.PlaneGeometry(18,650),0x303438,4,.025,0);road.rotation.x=-Math.PI/2;
const river=mesh(new THREE.PlaneGeometry(23,650),0x327e9c,-35,.02,0);river.rotation.x=-Math.PI/2;river.material.roughness=.15;river.material.metalness=.15;
function building(x,z,w,d,h,c,shop){let b=mesh(new THREE.BoxGeometry(w,h,d),c,x,h/2,z);for(let yy=2;yy<h-1;yy+=3.1)for(let xx=-w/2+2;xx<w/2-1;xx+=3){let win=mesh(new THREE.PlaneGeometry(1.35,1.65),0x92bfd0,x+xx,yy,z+d/2+.012);win.material.metalness=.4}if(shop){let fascia=mesh(new THREE.BoxGeometry(w*.78,1,.3),0x392719,x,2.9,z+d/2+.25);fascia.userData.shop=shop}return b}
const props=[{name:'Boulangerie du Grund',type:'Bäckerei',x:17,z:5,buy:485000,rent:3200},{name:'Café Alzette',type:'Café',x:17,z:-28,buy:620000,rent:4100},{name:'City Market',type:'Lebensmittel',x:-7,z:42,buy:790000,rent:5200}];
const colors=[0xcdb38d,0xb8755a,0xd2c6ae,0xaeb7aa,0xc9a16e];for(let z=-260,i=0;z<260;z+=25,i++){building(18,z,18,17,10+(i%4)*3,colors[i%colors.length],props.find(p=>Math.abs(p.z-z)<10)?.name);building(-7,z+10,17,16,9+((i+2)%5)*2,colors[(i+2)%colors.length])}
for(let z=-250;z<250;z+=18){let t=mesh(new THREE.CylinderGeometry(.25,.35,4,8),0x5a3c24,-21,2,z);mesh(new THREE.SphereGeometry(2.5,10,8),0x426c35,-21,5,z)}
function makePerson(){const skin=parseInt($('#skin').value,16), shirt=parseInt($('#shirt').value.slice(1),16), pants=parseInt($('#pants').value.slice(1),16), shoes=parseInt($('#shoes').value.slice(1),16);let g=new THREE.Group();const add=(geo,c,x,y,z)=>{let m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:c,roughness:.8}));m.position.set(x,y,z);m.castShadow=true;g.add(m);return m};add(new THREE.CapsuleGeometry(.47,1.15,5,12),shirt,0,2.25,0);add(new THREE.SphereGeometry(.43,20,16),skin,0,3.48,0);add(new THREE.CapsuleGeometry(.18,1.05,4,8),pants,-.27,.9,0);add(new THREE.CapsuleGeometry(.18,1.05,4,8),pants,.27,.9,0);add(new THREE.BoxGeometry(.42,.25,.72),shoes,-.27,.22,.13);add(new THREE.BoxGeometry(.42,.25,.72),shoes,.27,.22,.13);let hair=$('#hair').value,hh=hair==='long'?1.25:hair==='medium'?.65:.28;add(new THREE.SphereGeometry(.46,16,12),parseInt($('#hairColor').value.slice(1),16),0,3.7,-.04).scale.set(1,hh,.85);return g}
let player,started=false,money=125000,owned=[];const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='e')openNearest()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function listProps(){plist.innerHTML=props.map((p,i)=>`<div class="prop"><h3>${p.name}</h3><small>${p.type} · Grund</small><p>Kauf: ${p.buy.toLocaleString('de-DE')} €<br>Miete: ${p.rent.toLocaleString('de-DE')} €/Monat</p><div class="actions"><button onclick="window.deal(${i},'buy')">Kaufen</button><button onclick="window.deal(${i},'rent')">Mieten</button></div></div>`).join('')}
window.deal=(i,mode)=>{let p=props[i],cost=mode==='buy'?p.buy:p.rent;if(money<cost){alert('Nicht genug Geld.');return}money-=cost;owned.push(p.name);$('#money').textContent=money.toLocaleString('de-DE')+' €';alert(p.name+' wurde '+(mode==='buy'?'gekauft.':'gemietet.'))};
function openNearest(){let p=props.reduce((a,b)=>Math.hypot(player.position.x-b.x,player.position.z-b.z)<Math.hypot(player.position.x-a.x,player.position.z-a.z)?b:a);if(Math.hypot(player.position.x-p.x,player.position.z-p.z)<18){$('#ptitle').textContent=p.name;plist.innerHTML=`<div class="prop"><h3>${p.type}</h3><p>Gewerbeimmobilie im Grund.</p><p>Kaufpreis: ${p.buy.toLocaleString('de-DE')} €<br>Miete: ${p.rent.toLocaleString('de-DE')} €/Monat</p></div>`;panel.hidden=false}}
$('#property').onclick=()=>{listProps();panel.hidden=false};$('#close').onclick=()=>panel.hidden=true;
$('#go').onclick=()=>{player=makePerson();player.position.set(4,0,20);scene.add(player);creator.style.display='none';hud.hidden=false;tip.hidden=false;started=true};
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
let last=performance.now();function loop(t){requestAnimationFrame(loop);let dt=Math.min((t-last)/1000,.05);last=t;if(started){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let l=Math.hypot(dx,dz)||1;if(dx||dz){player.position.x+=dx/l*8*dt;player.position.z+=dz/l*8*dt;player.rotation.y=Math.atan2(dx,dz)}let target=new THREE.Vector3(player.position.x+9,7,player.position.z+12);camera.position.lerp(target,.07);camera.lookAt(player.position.x,2,player.position.z)}renderer.render(scene,camera)}loop(performance.now());