(()=>{const NS='http://www.w3.org/2000/svg',WORLD={min:-280,max:280},ROADS=[[-260,-210,260,-210],[-260,-90,260,-90],[-260,35,260,35],[-260,115,260,115],[-95,-260,-95,260],[92,-260,92,260],[210,-120,210,170]];
const houseFallback={studio:{x:-165,z:38},flat:{x:-176,z:55},family:{x:-190,z:72}};
const doorFallback={townhall:{x:-150,z:27},police:{x:92,z:-207.8},fire:{x:210,z:110.2},hospital:{x:-210,z:-75.8},bakery:{x:-92,z:-85.3},cafe:{x:91,z:-84.3},pub:{x:-91,z:98.2},mill:{x:91,z:101.7},sugar:{x:-92,z:230.2},bottler:{x:92,z:231.7},post:{x:-92,z:-205.3}};
const businessIcons={bakery:'B',cafe:'C',pub:'K',mill:'M',sugar:'Z',bottler:'W',post:'P'};
let mini,miniSvg,miniLayer,miniFoot,big,bigSvg,bigLayer,waypoint=null,wayHud=null;
const body=()=>document.body,ready=()=>body()?.classList.contains('game-ready'),W=()=>window.LuxWorld,H=()=>window.LuxHomes520,C=()=>window.LuxCivic404,S=()=>window.LuxSystems330,E=()=>window.LuxEconomy,A=()=>window.LuxAccount,SA=()=>window.LuxServerAssets740||window.LuxServerAssets710,L=()=>window.LuxLife?.state;
function e(tag,a={},txt=''){let n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,String(v));if(txt)n.textContent=txt;return n}
function homeSpots(){return H()?.spots||houseFallback}function doors(){return S()?.doors||doorFallback}
function myHomes(){let spots=homeSpots(),uid=A()?.session?.user?.id,out=[];for(const h of SA()?.serverHomes||[]){if(h.owner!==uid&&h.tenant!==uid)continue;let id=h.kind==='haus'?'family':'flat',p=spots[id];if(p)out.push({id,x:p.x,z:p.z,label:h.label|| (id==='family'?'Mein Haus':'Meine Wohnung'),kind:'home',sub:h.owner===uid?'Eigentum':'Miete'})}
 if(!out.length){let c=C()?.state?.home,id=c?.id;if(['studio','flat','family'].includes(id)&&spots[id])out.push({id,x:spots[id].x,z:spots[id].z,label:c?.name||'Mein Zuhause',kind:'home',sub:C()?.state?.owned?'Eigentum':'Miete'});else if((L()?.starterMonths||0)>0&&spots.flat)out.push({id:'flat',x:spots.flat.x,z:spots.flat.z,label:'Gemeinde-Startwohnung',kind:'home',sub:'Gemeinde'})}
 return out}
function myBusinesses(){let eco=E(),ds=doors();if(!eco?.myBusinesses)return[];return(eco.myBusinesses()||[]).map(id=>{let p=ds[id];return p?{id,x:p.x,z:p.z,label:eco.ECON?.nodes?.[id]?.name||id,kind:'business',sub:'Meine Firma'}:null}).filter(Boolean)}
function mapPlayer(){let w=W(),h=H(),homes=myHomes();if(!w?.player)return{x:0,z:0,inside:false};if(h?.inside&&homes.length)return{x:homes[0].x,z:homes[0].z,inside:true};return{x:w.player.position.x,z:w.player.position.z,inside:false}}
function addRoads(g,fn,width){for(const r of ROADS){let a=fn(r[0],r[1]),b=fn(r[2],r[3]);g.appendChild(e('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#5b6770','stroke-width':width,'stroke-linecap':'round',opacity:.72}))}}
function makeStyle(){let s=document.createElement('style');s.textContent=`
#luxMini830{position:fixed;right:12px;bottom:12px;z-index:59;width:184px;background:#091119e8;color:#fff;border:1px solid #ffffff30;border-radius:18px;overflow:hidden;box-shadow:0 12px 38px #0009;backdrop-filter:blur(9px);font:11px Arial;pointer-events:auto}#luxMini830[hidden]{display:none!important}
#luxMini830 .mh{height:28px;display:flex;align-items:center;justify-content:space-between;padding:0 9px;background:#0e1821;border-bottom:1px solid #ffffff17;font-weight:900}#luxMini830 .mh small{font-size:8px;color:#9aabb6}#luxMini830 svg{display:block;width:184px;height:150px;background:#142128}#luxMini830 .mf{height:27px;display:flex;align-items:center;padding:0 9px;border-top:1px solid #ffffff15;color:#ced7dd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#luxBig830{position:fixed;inset:0;z-index:180;background:#05090dde;display:grid;place-items:center;padding:14px;color:#fff;font:13px Arial;backdrop-filter:blur(10px)}#luxBig830[hidden]{display:none!important}.bigCard830{width:min(900px,96vw);max-height:92vh;overflow:auto;background:#0d151d;border:1px solid #ffffff25;border-radius:20px}.bigHead830{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #ffffff18}.bigHead830 button{background:#ffffff15;color:#fff;padding:7px 10px}.bigGrid830{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:12px;padding:12px}.bigMap830{border-radius:15px;overflow:hidden;background:#142128}.bigMap830 svg{display:block;width:100%;height:auto}.bigSide830{display:flex;flex-direction:column;gap:9px}.bigBox830{background:#151f28;border:1px solid #ffffff12;border-radius:12px;padding:10px}.bigBox830 b{display:block}.bigBox830 small{display:block;color:#9baab4;margin-top:4px}.bigBox830 button{width:100%;margin-top:8px;padding:8px}
#way830{position:fixed;left:50%;bottom:58px;transform:translateX(-50%);z-index:60;background:#091119e8;color:#fff;border:1px solid #ffffff28;border-radius:11px;padding:7px 10px;display:flex;gap:8px;align-items:center;font:bold 11px Arial}#way830[hidden]{display:none!important}#way830 .arr{font-size:21px;display:inline-block}#way830 button{padding:3px 6px;background:#ffffff14;color:#fff;font-size:9px}
body:not(.game-ready) #luxMini830{display:none!important}
@media(max-width:900px) and (orientation:landscape){#luxMini830{width:144px;right:7px;bottom:7px;border-radius:13px}#luxMini830 svg{width:144px;height:108px}#luxMini830 .mh{height:24px;font-size:9px;padding:0 6px}#luxMini830 .mf{height:23px;font-size:8px;padding:0 6px}}
@media(max-width:700px){.bigGrid830{grid-template-columns:1fr}.bigSide830{display:grid;grid-template-columns:1fr 1fr}.bigSide830 .bigBox830:last-child{grid-column:1/-1}}
@media(max-width:520px) and (orientation:portrait){#luxMini830{width:136px;right:6px;bottom:72px}#luxMini830 svg{width:136px;height:103px}}
`;document.head.appendChild(s)}
function build(){
 makeStyle();mini=document.createElement('aside');mini.id='luxMini830';mini.hidden=true;mini.innerHTML='<div class="mh"><span>🗺️ LUX CITY</span><small>ANTIPPEN = GROSS</small></div><svg id="miniSvg830" viewBox="0 0 290 230" aria-label="Dauerhafte Minimap"><defs><clipPath id="clip830"><rect x="2" y="2" width="286" height="226" rx="18"/></clipPath></defs><g id="miniLayer830" clip-path="url(#clip830)"></g></svg><div class="mf" id="miniFoot830">Orientierung</div>';document.body.appendChild(mini);miniSvg=document.getElementById('miniSvg830');miniLayer=document.getElementById('miniLayer830');miniFoot=document.getElementById('miniFoot830');mini.onclick=openBig;
 big=document.createElement('section');big.id='luxBig830';big.hidden=true;big.innerHTML='<div class="bigCard830"><div class="bigHead830"><b>🗺️ Lux City Karte</b><button id="bigClose830">✕</button></div><div class="bigGrid830"><div class="bigMap830"><svg id="bigSvg830" viewBox="0 0 600 600" aria-label="Große Lux City Karte"><g id="bigLayer830"></g></svg></div><aside class="bigSide830"><div class="bigBox830" id="homeBox830"></div><div class="bigBox830" id="firmBox830"></div><div class="bigBox830"><b>Bedienung</b><small>M öffnet/schließt die große Karte. Die kleine Karte bleibt beim Spielen immer sichtbar.</small></div></aside></div></div>';document.body.appendChild(big);bigSvg=document.getElementById('bigSvg830');bigLayer=document.getElementById('bigLayer830');document.getElementById('bigClose830').onclick=closeBig;
 wayHud=document.createElement('div');wayHud.id='way830';wayHud.hidden=true;wayHud.innerHTML='<span class="arr">↑</span><span class="wtxt"></span><button id="wayClear830">✕</button>';document.body.appendChild(wayHud);document.getElementById('wayClear830').onclick=()=>{waypoint=null;wayHud.hidden=true};
 addEventListener('keydown',ev=>{if(ev.repeat||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(ev.code==='KeyM'||String(ev.key).toLowerCase()==='m'){ev.preventDefault();big.hidden?openBig():closeBig()}if(ev.code==='Escape'&&!big.hidden){ev.preventDefault();closeBig()}});
}
function miniXY(x,z,cx,cz){let sc=0.72;return{x:145+(x-cx)*sc,y:115-(z-cz)*sc}}
function drawMini(){
 if(!ready()||!W()?.player){mini.hidden=true;return}mini.hidden=false;let p=mapPlayer(),cx=p.x,cz=p.z;miniLayer.innerHTML='';miniLayer.appendChild(e('rect',{x:0,y:0,width:290,height:230,fill:'#142128'}));addRoads(miniLayer,(x,z)=>miniXY(x,z,cx,cz),4);
 let points=[...myHomes(),...myBusinesses()];for(const o of points){let m=miniXY(o.x,o.z,cx,cz),dx=m.x-145,dy=m.y-115,d=Math.hypot(dx,dy),max=101;if(d>max){m.x=145+dx/d*max;m.y=115+dy/d*max}let col=o.kind==='home'?'#f2aa1b':'#6db9ff';miniLayer.appendChild(e('circle',{cx:m.x,cy:m.y,r:o.kind==='home'?6:5,fill:col,stroke:'#071017','stroke-width':2}));miniLayer.appendChild(e('text',{x:m.x,y:m.y+3,'text-anchor':'middle','font-size':'7','font-weight':'900',fill:'#071017'},o.kind==='home'?'H':businessIcons[o.id]||'F'))}
 miniLayer.appendChild(e('circle',{cx:145,cy:115,r:7,fill:'#59e78a',stroke:'#071017','stroke-width':2}));miniLayer.appendChild(e('text',{x:145,y:118,'text-anchor':'middle','font-size':'8','font-weight':'900',fill:'#071017'},'▲'));
 let nearest=points.map(o=>({...o,d:Math.round(Math.hypot(o.x-cx,o.z-cz))})).sort((a,b)=>a.d-b.d)[0];miniFoot.textContent=p.inside?'IN DEINER WOHNUNG':nearest?nearest.label+' · '+nearest.d+' m':'DU · LUX CITY';updateWay(p)
}
function bigXY(x,z){return{x:(x-WORLD.min)/(WORLD.max-WORLD.min)*600,y:(WORLD.max-z)/(WORLD.max-WORLD.min)*600}}
function markBig(o,col,txt){let m=bigXY(o.x,o.z);bigLayer.appendChild(e('circle',{cx:m.x,cy:m.y,r:8,fill:col,stroke:'#071017','stroke-width':3}));bigLayer.appendChild(e('text',{x:m.x+12,y:m.y+4,fill:'#fff','font-size':'10','font-weight':'800'},txt))}
function renderBig(){bigLayer.innerHTML='';bigLayer.appendChild(e('rect',{x:0,y:0,width:600,height:600,fill:'#142128'}));addRoads(bigLayer,bigXY,8);for(const h of myHomes())markBig(h,'#f2aa1b','🏠 '+h.label);for(const f of myBusinesses())markBig(f,'#6db9ff','◆ '+f.label);let ds=doors();for(const [name,id] of [['Gemeinde','townhall'],['Polizei','police'],['Feuerwehr','fire'],['Krankenhaus','hospital']]){let p=ds[id];if(p)markBig({...p},'#aeb8bf',name)}let p=mapPlayer();markBig(p,'#59e78a','DU');
 let hb=document.getElementById('homeBox830'),homes=myHomes();hb.innerHTML=homes.length?'<b>Meine Immobilien</b>'+homes.map((h,i)=>'<button data-home830="'+i+'">'+h.label+' · '+h.sub+'</button>').join(''):'<b>Meine Immobilien</b><small>Noch kein Zuhause gefunden.</small>';hb.querySelectorAll('[data-home830]').forEach(b=>b.onclick=()=>{let h=homes[Number(b.dataset.home830)];waypoint={x:h.x,z:h.z,label:h.label};closeBig();updateWay(mapPlayer())});
 let fb=document.getElementById('firmBox830'),firms=myBusinesses();fb.innerHTML=firms.length?'<b>Meine Firmen</b>'+firms.map((f,i)=>'<button data-firm830="'+i+'">'+f.label+'</button>').join(''):'<b>Meine Firmen</b><small>Noch keine eigene Firma.</small>';fb.querySelectorAll('[data-firm830]').forEach(b=>b.onclick=()=>{let f=firms[Number(b.dataset.firm830)];waypoint={x:f.x,z:f.z,label:f.label};closeBig();updateWay(mapPlayer())})
}
function updateWay(p){if(!waypoint||!W()?.player){wayHud.hidden=true;return}let dx=waypoint.x-p.x,dz=waypoint.z-p.z,d=Math.hypot(dx,dz);wayHud.hidden=false;let rel=Math.atan2(dx,dz)-(W().yaw||0);wayHud.querySelector('.arr').style.transform='rotate('+(rel*180/Math.PI)+'deg)';wayHud.querySelector('.wtxt').textContent=d<3?waypoint.label+' erreicht':waypoint.label+' · '+Math.round(d)+' m'}
function openBig(){if(!ready())return;renderBig();big.hidden=false}function closeBig(){big.hidden=true}
build();setInterval(drawMini,160);addEventListener('luxcity:manual-login',()=>setTimeout(drawMini,100));window.LuxNavigation830={open:openBig,close:closeBig,refresh:drawMini,myHomes,myBusinesses,setWaypoint:o=>{waypoint=o;updateWay(mapPlayer())}};window.LuxCityMap810={open:openBig,close:closeBig,toggle:()=>big.hidden?openBig():closeBig,currentHome:()=>myHomes()[0]||null,setWaypointHome(){let h=myHomes()[0];if(!h)return false;waypoint={x:h.x,z:h.z,label:h.label};updateWay(mapPlayer());return true}}})();