(()=>{const NS='http://www.w3.org/2000/svg';let mini,ml,mf,big,bl,way=null,wayHud=null;
const W=()=>window.LuxWorld,H=()=>window.LuxHomes520,A=()=>window.LuxAccount,SA=()=>window.LuxServerAssets740||window.LuxServerAssets710,E=()=>window.LuxEconomy,S=()=>window.LuxSystems330,C=()=>window.LuxCivic404,L=()=>window.LuxLife?.state,ready=()=>document.body.classList.contains('game-ready');
function e(t,a={},x=''){let n=document.createElementNS(NS,t);for(const[k,v]of Object.entries(a))n.setAttribute(k,String(v));if(x)n.textContent=x;return n}
function ownHome(){let ha=window.LuxHomeAccess840?.resolve?.();if(ha)return{...ha,kind:'home'};return null}
function businesses(){let eco=E(),ds=S()?.doors||{};if(!eco?.myBusinesses)return[];return(eco.myBusinesses()||[]).map(id=>{let p=ds[id];return p?{id,x:p.x,z:p.z,label:eco.ECON?.nodes?.[id]?.name||id,kind:'business'}:null}).filter(Boolean)}
function outsidePlayer(){let w=W(),h=H(),home=ownHome();if(!w?.player)return{x:0,z:0};if(h?.inside&&home)return{x:home.x,z:home.z};return{x:w.player.position.x,z:w.player.position.z}}
function roadLines(g,fn,width){for(const r of W()?.roads||[]){let hx=r.l/2,hz=r.w/2,a,b;if(hz>hx){a=fn(r.x,r.z-hz);b=fn(r.x,r.z+hz)}else{a=fn(r.x-hx,r.z);b=fn(r.x+hx,r.z)}g.appendChild(e('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#68737c','stroke-width':width,'stroke-linecap':'round',opacity:.72}))}}
function housePoint(i,h){return{x:h.x,z:h.z,label:'Haus '+(i+1),kind:'house'}}
function homeHouseIndex(home){let sh=(SA()?.serverHomes||[]).find(h=>String(h.id)===String(home?.serverId));if(sh?.kind==='haus'){let n=Number(sh.id);return Number.isFinite(n)?Math.max(0,n-41):0}return-1}
function miniXY(x,z,p){let scale=.62;return{x:108+(x-p.x)*scale,y:108-(z-p.z)*scale}}
function clipped(pt){let dx=pt.x-108,dy=pt.y-108,d=Math.hypot(dx,dy),m=94;if(d>m)return{x:108+dx/d*m,y:108+dy/d*m};return pt}
function drawMini(){
 if(!ready()||!W()?.player){mini.hidden=true;return}mini.hidden=false;let p=outsidePlayer(),yaw=W().yaw||0;ml.innerHTML='';ml.appendChild(e('circle',{cx:108,cy:108,r:104,fill:'#111b23'}));
 roadLines(ml,(x,z)=>miniXY(x,z,p),5);
 let home=ownHome(),hi=homeHouseIndex(home),sites=W().houseSites||[];
 sites.forEach((h,i)=>{let m=clipped(miniXY(h.x,h.z,p));ml.appendChild(e('circle',{cx:m.x,cy:m.y,r:i===hi?4.8:2.2,fill:i===hi?'#f2ad23':'#89959d',opacity:i===hi?1:.55}))});
 if(home&&hi<0){let m=clipped(miniXY(home.x,home.z,p));ml.appendChild(e('circle',{cx:m.x,cy:m.y,r:5.2,fill:'#f2ad23',stroke:'#111','stroke-width':2}));ml.appendChild(e('text',{x:m.x,y:m.y+3,'text-anchor':'middle','font-size':'7','font-weight':'900'},'H'))}
 for(const b of businesses()){let m=clipped(miniXY(b.x,b.z,p));ml.appendChild(e('circle',{cx:m.x,cy:m.y,r:4.5,fill:'#65b8ff',stroke:'#111','stroke-width':2}))}
 let guide=way||home;if(guide){let m=clipped(miniXY(guide.x,guide.z,p));ml.appendChild(e('line',{x1:108,y1:108,x2:m.x,y2:m.y,stroke:'#f0a51a','stroke-width':2.5,'stroke-dasharray':'5 4',opacity:.95}));ml.appendChild(e('circle',{cx:m.x,cy:m.y,r:6,fill:'#f0a51a',stroke:'#fff','stroke-width':1.5}))}
 let arrow=e('path',{d:'M108 94 L114 112 L108 109 L102 112 Z',fill:'#61e493',stroke:'#07110d','stroke-width':2,transform:'rotate('+((yaw||0)*180/Math.PI)+' 108 108)'});ml.appendChild(arrow);
 let pts=[...(home?[home]:[]),...businesses()].map(o=>({...o,d:Math.round(Math.hypot(o.x-p.x,o.z-p.z))})).sort((a,b)=>a.d-b.d),
 target=way||home||pts[0];
 if(target){let dx=target.x-p.x,dz=target.z-p.z,d=Math.round(Math.hypot(dx,dz)),ang=Math.atan2(dx,dz),rel=ang-(yaw||0);while(rel>Math.PI)rel-=Math.PI*2;while(rel<-Math.PI)rel+=Math.PI*2;let dirs=['↑','↗','→','↘','↓','↙','←','↖'],idx=Math.round((((rel*180/Math.PI)+360)%360)/45)%8;mf.textContent=(target===way?'ZIEL · ':'🏠 ')+(target.label||'Zuhause')+' · '+d+' m '+dirs[idx]}else mf.textContent='LUX CITY · NORDEN ↑'
 updateWay(p)
}
function bounds(){let xs=[],zs=[];for(const r of W()?.roads||[]){xs.push(r.x-r.l/2,r.x+r.l/2);zs.push(r.z-r.l/2,r.z+r.l/2)}for(const h of W()?.houseSites||[]){xs.push(h.x);zs.push(h.z)}return{minX:Math.min(-320,...xs)-15,maxX:Math.max(320,...xs)+15,minZ:Math.min(-320,...zs)-15,maxZ:Math.max(320,...zs)+15}}
function bigXY(x,z,b){return{x:(x-b.minX)/(b.maxX-b.minX)*640,y:(b.maxZ-z)/(b.maxZ-b.minZ)*640}}
function mark(g,o,b,col,label,r=6){let m=bigXY(o.x,o.z,b);g.appendChild(e('circle',{cx:m.x,cy:m.y,r,fill:col,stroke:'#071017','stroke-width':2}));if(label)g.appendChild(e('text',{x:m.x+9,y:m.y+3,fill:'#fff','font-size':'9','font-weight':'800'},label))}
function renderBig(){
 let b=bounds();bl.innerHTML='';bl.appendChild(e('rect',{x:0,y:0,width:640,height:640,fill:'#111b23'}));roadLines(bl,(x,z)=>bigXY(x,z,b),9);
 let home=ownHome(),hi=homeHouseIndex(home),sites=W().houseSites||[];
 sites.forEach((h,i)=>{let o=housePoint(i,h),m=bigXY(o.x,o.z,b),mine=i===hi;bl.appendChild(e('rect',{x:m.x-(mine?5:3),y:m.y-(mine?5:3),width:mine?10:6,height:mine?10:6,rx:1,fill:mine?'#f2ad23':'#7f8a91',stroke:mine?'#fff':'#111','stroke-width':mine?1.5:.6,opacity:mine?1:.78}));if(mine)bl.appendChild(e('text',{x:m.x+9,y:m.y+3,fill:'#fff','font-size':'10','font-weight':'900'},home?.label||'MEIN HAUS'))});
 if(home&&hi<0)mark(bl,home,b,'#f2ad23','🏠 '+home.label,7);
 for(const f of businesses())mark(bl,f,b,'#65b8ff','◆ '+f.label,6);
 let ds=S()?.doors||{};for(const [id,label] of [['townhall','Gemeinde'],['police','Polizei'],['fire','Feuerwehr'],['hospital','Krankenhaus']])if(ds[id])mark(bl,ds[id],b,'#b8c0c6',label,4);
 mark(bl,outsidePlayer(),b,'#61e493','DU',7);
 let hb=document.getElementById('navHome840');if(home)hb.innerHTML='<b>🏠 '+home.label+'</b><small>'+home.kind+(home.serverId?' · Besitz/Miete':'')+'</small><button id="navHomeWp840">WEGPUNKT SETZEN</button>';else hb.innerHTML='<b>Kein Zuhause gefunden</b><small>Deine Gemeinde-Wohnung oder Immobilie erscheint automatisch.</small>';
 document.getElementById('navHomeWp840')?.addEventListener('click',()=>{way={x:home.x,z:home.z,label:home.label};closeBig();updateWay(outsidePlayer())});
 let fb=document.getElementById('navFirm840'),fs=businesses();fb.innerHTML=fs.length?'<b>Meine Firmen</b>'+fs.map((f,i)=>'<button data-fwp="'+i+'">'+f.label+'</button>').join(''):'<b>Meine Firmen</b><small>Noch keine eigene Firma.</small>';fb.querySelectorAll('[data-fwp]').forEach(x=>x.onclick=()=>{let f=fs[Number(x.dataset.fwp)];way={x:f.x,z:f.z,label:f.label};closeBig();updateWay(outsidePlayer())})
}
function updateWay(p){if(!way||!W()?.player){wayHud.hidden=true;return}let dx=way.x-p.x,dz=way.z-p.z,d=Math.hypot(dx,dz),rel=Math.atan2(dx,dz)-(W().yaw||0);wayHud.hidden=false;wayHud.querySelector('.arr').style.transform='rotate('+(rel*180/Math.PI)+'deg)';wayHud.querySelector('.txt').textContent=d<3?way.label+' erreicht':way.label+' · '+Math.round(d)+' m'}
function openBig(){if(!ready())return;renderBig();big.hidden=false}function closeBig(){big.hidden=true}
function build(){
 let css=document.createElement('style');css.textContent=`
 #navMini840{position:fixed;right:12px;top:58px;bottom:auto;z-index:58;width:192px;height:210px;color:#fff;font:11px Arial;pointer-events:auto}#navMini840[hidden]{display:none!important}.radar840{width:192px;height:192px;border-radius:50%;overflow:hidden;background:#111b23dd;border:3px solid #ffffff30;box-shadow:0 10px 34px #000a;backdrop-filter:blur(7px)}.radar840 svg{width:192px;height:192px;display:block}.navFoot840{margin:-2px auto 0;width:178px;background:#0a121be8;border:1px solid #ffffff22;border-radius:0 0 10px 10px;padding:5px 8px;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
 #navBig840{position:fixed;inset:0;z-index:180;background:#03070bdc;display:grid;place-items:center;padding:14px;color:#fff;font:13px Arial;backdrop-filter:blur(10px)}#navBig840[hidden]{display:none!important}.navCard840{width:min(930px,96vw);max-height:93vh;overflow:auto;background:#0d151d;border:1px solid #ffffff24;border-radius:20px}.navHead840{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border-bottom:1px solid #ffffff18}.navHead840 button{background:#ffffff14;color:#fff;padding:7px 10px}.navGrid840{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:12px;padding:12px}.navMap840{border-radius:15px;overflow:hidden}.navMap840 svg{display:block;width:100%;height:auto}.navSide840{display:flex;flex-direction:column;gap:9px}.navBox840{background:#151f28;border:1px solid #ffffff12;border-radius:12px;padding:10px}.navBox840 small{display:block;color:#9aaab5;margin-top:4px}.navBox840 button{width:100%;margin-top:8px;padding:8px}
 #navWay840{position:fixed;left:50%;bottom:58px;transform:translateX(-50%);z-index:59;background:#0a121be8;color:#fff;border:1px solid #ffffff2b;border-radius:12px;padding:7px 10px;display:flex;align-items:center;gap:8px;font:bold 11px Arial}#navWay840[hidden]{display:none!important}#navWay840 .arr{display:inline-block;font-size:22px}#navWay840 button{padding:3px 6px;background:#ffffff13;color:#fff;font-size:9px}
 body:not(.game-ready) #navMini840{display:none!important}
 @media(max-width:900px) and (pointer:coarse){#navMini840{width:132px;height:147px;right:8px;top:48px;bottom:auto}.radar840{width:132px;height:132px;border-width:2px}.radar840 svg{width:132px;height:132px}.navFoot840{width:108px;font-size:8px;padding:3px 5px}.navGrid840{grid-template-columns:1fr}.navSide840{display:grid;grid-template-columns:1fr 1fr}.navCard840{width:98vw;max-height:96vh}.navHead840{padding:8px 10px}.navMap840 svg{max-height:66vh}.navBox840{padding:8px}.navBox840 button{padding:9px;font-size:12px}}
 @media(max-width:650px){.navGrid840{grid-template-columns:1fr}.navSide840{display:grid;grid-template-columns:1fr 1fr}}
 `;document.head.appendChild(css);
 mini=document.createElement('aside');mini.id='navMini840';mini.hidden=true;mini.innerHTML='<div class="radar840"><svg viewBox="0 0 216 216"><defs><clipPath id="radarClip840"><circle cx="108" cy="108" r="104"/></clipPath></defs><g id="navMiniLayer840" clip-path="url(#radarClip840)"></g><circle cx="108" cy="108" r="104" fill="none" stroke="#ffffff24" stroke-width="2"/><text x="108" y="13" text-anchor="middle" fill="#ffffff" font-size="10" font-weight="900">N ↑</text></svg></div><div class="navFoot840" id="navMiniFoot840">LUX CITY</div>';document.body.appendChild(mini);ml=document.getElementById('navMiniLayer840');mf=document.getElementById('navMiniFoot840');mini.onclick=openBig;
 big=document.createElement('section');big.id='navBig840';big.hidden=true;big.innerHTML='<div class="navCard840"><div class="navHead840"><b>🗺️ LUX CITY · STADTKARTE</b><button id="navClose840">✕</button></div><div class="navGrid840"><div class="navMap840"><svg viewBox="0 0 640 640"><g id="navBigLayer840"></g></svg></div><aside class="navSide840"><div class="navBox840" id="navHome840"></div><div class="navBox840" id="navFirm840"></div><div class="navBox840"><b>Legende</b><small>▦ Grau = Häuser · 🟨 Gold = dein Zuhause · 🔵 Blau = deine Firma · 🟢 Grün = du</small><small style="margin-top:7px">Die kleine Karte bleibt immer sichtbar. Antippen = große Karte.</small></div></aside></div></div>';document.body.appendChild(big);bl=document.getElementById('navBigLayer840');document.getElementById('navClose840').onclick=closeBig;
 wayHud=document.createElement('div');wayHud.id='navWay840';wayHud.hidden=true;wayHud.innerHTML='<span class="arr">↑</span><span class="txt"></span><button>✕</button>';document.body.appendChild(wayHud);wayHud.querySelector('button').onclick=()=>{way=null;wayHud.hidden=true};
 addEventListener('keydown',ev=>{if(ev.repeat||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(ev.code==='KeyM'||String(ev.key).toLowerCase()==='m'){ev.preventDefault();big.hidden?openBig():closeBig()}if(ev.code==='Escape'&&!big.hidden){ev.preventDefault();closeBig()}})
}
build();setInterval(drawMini,140);window.LuxNavigation840=window.LuxNavigation850=window.LuxNavigation860={open:openBig,close:closeBig,refresh:drawMini,ownHome,businesses};window.LuxNavigation830=window.LuxNavigation840;window.LuxCityMap810={open:openBig,close:closeBig,toggle:()=>big.hidden?openBig():closeBig,currentHome:ownHome,setWaypointHome(){let h=ownHome();if(!h)return false;way={x:h.x,z:h.z,label:h.label};return true}}
})();