(()=>{
const K='luxcity_phone_v100',P=[
{id:'luxprotect',name:'LuxProtect',m:62,sb:1000,c:'Haftpflicht'},
{id:'mosel',name:'Mosel Assur',m:79,sb:750,c:'Haftpflicht + Glas'},
{id:'nord',name:'NordSecure',m:104,sb:500,c:'Teilkasko'},
{id:'cite',name:'Cité Insurance',m:129,sb:250,c:'Vollkasko'}];
let S={insurance:{},tax:{},bills:[],mk:''};try{Object.assign(S,JSON.parse(localStorage.getItem(K)||'{}'))}catch{}S.insurance??={};S.tax??={};S.bills??=[];
const L=()=>window.LuxLife?.state,V=()=>window.LuxVehicles,A=()=>window.LuxAccount,eur=n=>Math.round(+n||0).toLocaleString('de-DE')+' €',save=()=>{localStorage.setItem(K,JSON.stringify(S));window.LuxCloud438?.save?.()},esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const mk=()=>{let l=L();return l?l.year+'-'+String(l.month).padStart(2,'0'):''},car=()=>V()?.activeVehicle||null;
function factor(v){let x=v?.type==='suv'?1.22:v?.type==='van'?1.28:1,f=v?.fuelType||v?.fuel_type||'petrol';return x*(f==='electric'?.88:f==='diesel'?1.12:1)}
function premium(v,p){return Math.max(35,Math.round(p.m*factor(v)))}
function taxDue(v){let f=v?.fuelType||v?.fuel_type||'petrol',t=v?.type||'compact';if(f==='electric')return t==='suv'?45:30;if(f==='diesel')return t==='van'?280:t==='suv'?245:195;return t==='suv'?185:125}
function debit(n){let l=L();n=Math.round(+n||0);if(!l||n<=0)return false;if(l.cash<n){alert('Nicht genug Geld.');return false}if(window.LuxLife?.addExpense)window.LuxLife.addExpense(n);else{l.cash-=n;window.LuxLife?.save?.()}return true}
function credit(n){let l=L();n=Math.round(+n||0);if(!l||n<=0)return;if(window.LuxLife?.addRevenue)window.LuxLife.addRevenue(n);else{l.cash+=n;window.LuxLife?.save?.()}}
function billsEnsure(){let key=mk();if(!key||S.mk===key)return;S.mk=key;S.bills.push({id:'water-'+key,t:'Wasser',a:32,k:'Gemeinde',paid:false},{id:'waste-'+key,t:'Müll & Tonnen',a:18,k:'Gemeinde',paid:false});for(let id in S.insurance){let c=S.insurance[id];if(c?.active)S.bills.push({id:'ins-'+id+'-'+key,t:c.name+' Autoversicherung',a:c.monthly,k:'Versicherung',paid:false})}save()}
let box,screen,opened=false;
function shell(){if(box)return;box=document.createElement('div');box.id='luxPhone100';box.style='position:fixed;right:16px;top:50%;transform:translateY(-50%);width:min(360px,92vw);height:min(680px,90vh);z-index:96;background:#090c10;color:#fff;border:7px solid #252a32;border-radius:34px;overflow:hidden;box-shadow:0 20px 70px #000c;font-family:Arial;display:none';box.innerHTML='<div style="height:34px;text-align:center;padding-top:8px">LUX CITY PHONE</div><div id="phScreen" style="height:calc(100% - 92px);overflow:auto;padding:14px;background:linear-gradient(160deg,#17283d,#0b1119)"></div><div style="height:44px;display:flex;justify-content:space-around;align-items:center;border-top:1px solid #ffffff22"><button id="phBack">‹</button><button id="phHome">●</button><button id="phClose">✕</button></div>';document.body.appendChild(box);screen=box.querySelector('#phScreen');box.querySelector('#phHome').onclick=home;box.querySelector('#phBack').onclick=home;box.querySelector('#phClose').onclick=()=>toggle(false)}
function app(icon,name,sub,id){return '<button data-app="'+id+'" style="background:#ffffff12;color:#fff;text-align:left;min-height:92px;border:1px solid #ffffff18"><span style="font-size:27px">'+icon+'</span><br><b>'+name+'</b><br><small>'+sub+'</small></button>'}
function home(){billsEnsure();screen.innerHTML='<h2 style="margin-top:0">Hallo '+esc(A()?.profile?.player_name||'Spieler')+'</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">'+app('🏦','Bank','Kontostand & Überweisen','bank')+app('🛡️','Versicherung','4 Anbieter vergleichen','ins')+app('🚗','Steuern','Kfz-Steuer','tax')+app('🧾','Rechnungen','Wasser, Müll, Versicherung','bills')+'</div>';screen.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openApp(b.dataset.app))}
async function claim(){let a=A(),uid=a?.session?.user?.id;if(!a?.sb||!uid)return;let r=await a.sb.from('player_transfers').select('id,amount').eq('recipient',uid).is('claimed_at',null);if(r.error||!r.data?.length)return;let total=r.data.reduce((n,x)=>n+(+x.amount||0),0),now=new Date().toISOString();for(let x of r.data)await a.sb.from('player_transfers').update({claimed_at:now}).eq('id',x.id).eq('recipient',uid);credit(total)}
async function send(){let a=A(),uid=a?.session?.user?.id,name=screen.querySelector('#phTo')?.value.trim(),amount=Math.round(+screen.querySelector('#phAmt')?.value||0);if(!a?.sb||!uid)return alert('Nicht angemeldet.');if(!name||amount<=0)return alert('Spielername und Betrag eingeben.');if((L()?.cash||0)<amount)return alert('Nicht genug Geld.');let r=await a.sb.from('profiles').select('id,player_name').ilike('player_name',name).limit(2);if(r.error||!r.data?.length)return alert('Spieler nicht gefunden.');if(r.data.length!==1)return alert('Spielername nicht eindeutig.');if(r.data[0].id===uid)return alert('Überweisung an dich selbst ist nicht möglich.');let x=await a.sb.from('player_transfers').insert({sender:uid,recipient:r.data[0].id,amount});if(x.error)return alert('Überweisung fehlgeschlagen.');if(!debit(amount))return;alert(eur(amount)+' an '+r.data[0].player_name+' überwiesen.');bank()}
async function bank(){await claim();screen.innerHTML='<h2>🏦 Lux City Bank</h2><h1>'+eur(L()?.cash||0)+'</h1><h3>Spielerüberweisung</h3><input id="phTo" placeholder="Spielername" style="width:100%;box-sizing:border-box"><input id="phAmt" type="number" min="1" placeholder="Betrag in €" style="width:100%;box-sizing:border-box;margin-top:7px"><button id="phSend" style="width:100%;margin-top:7px">ÜBERWEISEN</button><button id="phLoan" style="width:100%;margin-top:10px">KREDITE & BONITÄT</button>';screen.querySelector('#phSend').onclick=send;screen.querySelector('#phLoan').onclick=()=>{toggle(false);window.LuxBank442?.bank?.()}}
function insurance(){let v=car();if(!v){screen.innerHTML='<h2>🛡️ Versicherung</h2><p>Kein Fahrzeug ausgewählt.</p>';return}let c=S.insurance[v.id];screen.innerHTML='<h2>🛡️ Autoversicherung</h2><p><b>'+esc(v.name)+'</b></p>'+(c?.active?'<p>Aktiv: <b>'+esc(c.name)+'</b> · '+eur(c.monthly)+'/Monat</p>':'')+P.map(p=>'<div style="background:#ffffff10;padding:10px;margin:7px 0;border-radius:12px"><b>'+p.name+'</b><br><small>'+p.c+' · Selbstbeteiligung '+eur(p.sb)+'</small><br><b>'+eur(premium(v,p))+'/Monat</b> <button data-ins="'+p.id+'">WÄHLEN</button></div>').join('');screen.querySelectorAll('[data-ins]').forEach(b=>b.onclick=()=>{let p=P.find(x=>x.id===b.dataset.ins),m=premium(v,p);if(c?.id===p.id)return alert('Bereits aktiv.');if(!debit(m))return;S.insurance[v.id]={active:true,id:p.id,name:p.name,monthly:m,cover:p.c,sb:p.sb};save();insurance()})}
function tax(){let v=car();if(!v){screen.innerHTML='<h2>🚗 Kfz-Steuer</h2><p>Kein Fahrzeug ausgewählt.</p>';return}let year=L()?.year||2026,due=taxDue(v),paid=S.tax[v.id]?.year===year;screen.innerHTML='<h2>🚗 Kfz-Steuer</h2><p><b>'+esc(v.name)+'</b></p><h1>'+eur(due)+'</h1><p>Steuerjahr '+year+' · '+(paid?'✅ bezahlt':'⚠️ offen')+'</p>'+(paid?'':'<button id="phTax">JETZT ZAHLEN</button>');let b=screen.querySelector('#phTax');if(b)b.onclick=()=>{if(!debit(due))return;S.tax[v.id]={year,amount:due,paidAt:Date.now()};save();tax()}}
function bills(){billsEnsure();let o=S.bills.filter(x=>!x.paid);screen.innerHTML='<h2>🧾 Rechnungen</h2>'+(o.length?o.map(x=>'<div style="background:#ffffff10;padding:10px;margin:7px 0;border-radius:12px"><b>'+esc(x.t)+'</b><br><small>'+esc(x.k)+'</small><br><b>'+eur(x.a)+'</b> <button data-bill="'+esc(x.id)+'">ZAHLEN</button></div>').join(''):'<p>✅ Keine offenen Rechnungen.</p>');screen.querySelectorAll('[data-bill]').forEach(b=>b.onclick=()=>{let x=S.bills.find(q=>q.id===b.dataset.bill);if(!x||x.paid||!debit(x.a))return;x.paid=true;x.paidAt=Date.now();save();bills()})}
function openApp(id){if(id==='bank')bank();if(id==='ins')insurance();if(id==='tax')tax();if(id==='bills')bills()}
function toggle(force){shell();opened=typeof force==='boolean'?force:!opened;box.style.display=opened?'block':'none';if(opened)home()}
addEventListener('keydown',e=>{let t=document.activeElement?.tagName;if(t==='INPUT'||t==='TEXTAREA'||t==='SELECT')return;if((e.code==='KeyH'||String(e.key).toLowerCase()==='h')&&!e.repeat&&document.body.classList.contains('game-ready')){e.preventDefault();e.stopImmediatePropagation();toggle()}},true);
function hud(){let h=document.getElementById('hud');if(!h||document.getElementById('phone100'))return;let b=document.createElement('button');b.id='phone100';b.textContent='📱 HANDY / H';b.onclick=()=>toggle();h.appendChild(b)}
setInterval(()=>{hud();billsEnsure()},900);shell();window.LuxPhone100={state:S,providers:P,toggle,openApp,save,taxDue,premium};
})();