(()=>{const ITEMS=[
['Figur realistischer','done'],['KI-Menschen realistischer','done'],['Häuser abwechslungsreicher','done'],['Öffentliche Gebäude überarbeiten','done'],['Fenster & Türen realistischer','done'],['Grundstücke & Zufahrten verbessern','done'],['Straßen realistischer','done'],['Ampeln überarbeiten','done'],['Zebrastreifen verbessern','done'],['Autos deutlich realistischer','done'],['Elektro/Benzin/Diesel optisch unterscheiden','done'],['KI-Verkehr verbessern','done'],['Beleuchtung realistischer','done'],['Performance optimieren','done'],['Abschlussprüfung & Fehlerbehebung','done']
],NEXT=[['Innenräume weiter realistischer','planned'],['Bewohner mit Tagesabläufen','planned'],['Parken, Garagen & Fahrzeugnutzung','planned'],['Geschäfte mit sichtbaren Kundenabläufen','planned'],['Weitere Performance- und Bugtests','planned']];
const host=document.getElementById('login');if(!host)return;let style=document.createElement('style');style.textContent=
'#roadmap720{position:absolute;z-index:8;left:18px;top:18px;width:min(340px,calc(100vw - 36px));background:#0b1118e8;border:1px solid #ffffff24;border-radius:14px;color:#fff;box-shadow:0 14px 45px #0008;backdrop-filter:blur(14px);font-family:Inter,Arial,sans-serif}'+
'#roadmap720 button{width:100%;display:flex;align-items:center;justify-content:space-between;background:transparent!important;color:#fff!important;padding:11px 13px!important;text-align:left;font-weight:900}'+
'#roadmap720 .rmBody{padding:0 13px 13px;max-height:58vh;overflow:auto}#roadmap720.collapsed .rmBody{display:none}'+
'#roadmap720 h3{font-size:13px;color:#f1b84b;margin:10px 0 7px}.rmRow{display:flex;gap:8px;align-items:flex-start;padding:7px 0;border-top:1px solid #ffffff10;font-size:12px;line-height:1.3}.rmState{flex:0 0 auto;border-radius:99px;padding:2px 6px;font-size:10px;font-weight:900}.rmDone{background:#244d33;color:#b9f2ca}.rmPlan{background:#273747;color:#b9d7ef}.rmNote{font-size:11px;color:#9eacb7;margin-top:8px;line-height:1.4}'+
'@media(max-width:860px){#roadmap720{position:relative;left:auto;top:auto;width:auto;margin:14px 16px 0}.authShell{padding-top:12px!important}}';
document.head.appendChild(style);let box=document.createElement('aside');box.id='roadmap720';box.className='collapsed';box.innerHTML='<button id="rmToggle720"><span>🛠️ NÄCHSTE UPDATES</span><span>＋</span></button><div class="rmBody"><h3>V7.2.0 · GRAFIK & REALISMUS</h3><div id="rmCurrent720"></div><h3>DANACH GEPLANT</h3><div id="rmNext720"></div><div class="rmNote">Neue Ideen werden zuerst hier aufgenommen und danach abgearbeitet. Erledigte Punkte bleiben sichtbar markiert.</div></div>';host.appendChild(box);
function rows(list){return list.map(([t,s],i)=>'<div class="rmRow"><span class="rmState '+(s==='done'?'rmDone':'rmPlan')+'">'+(s==='done'?'ERLEDIGT':'GEPLANT')+'</span><span>'+(i+1)+'. '+t+'</span></div>').join('')}document.getElementById('rmCurrent720').innerHTML=rows(ITEMS);document.getElementById('rmNext720').innerHTML=rows(NEXT);let b=document.getElementById('rmToggle720');b.onclick=()=>{box.classList.toggle('collapsed');b.lastElementChild.textContent=box.classList.contains('collapsed')?'＋':'−'};window.LuxRoadmap720={items:ITEMS,next:NEXT}})();