(()=>{const K="luxcity_systems_v330";let S;try{S=JSON.parse(localStorage.getItem(K)||"{}")}catch{S={}};Object.assign(S,{shift:S.shift||null,eviction:S.eviction||0,bankWarnings:S.bankWarnings||0,companyLock:!!S.companyLock});const save=()=>localStorage.setItem(K,JSON.stringify(S)),W=()=>window.LuxWorld,L=()=>window.LuxLife?.state,R=()=>window.LuxBusinessRisk?.state,G=()=>window.LuxGameplay?.state,money=n=>Math.round(+n||0).toLocaleString("de-DE")+" €";
const places={Bäcker:{x:-92,z:-85},Verkäufer:{x:-92,z:-85},Fahrer:{x:-92,z:-205},Barista:{x:91,z:-84},Kellner:{x:-91,z:98},Lagerist:{x:-92,z:-205},Reinigung:{x:-150,z:27},Polizist:{x:92,z:-208},Feuerwehr:{x:210,z:110},Rettungsdienst:{x:210,z:-77}};
function dist(a,b){return Math.hypot((a?.x||0)-b.x,(a?.z||0)-b.z)}
function shift(){return window.LuxWork412?.shift?.()}
function finance(){let l=L(),r=R();if(!l||!r)return;let ym=l.year+"-"+l.month;if(S.financeMonth===ym)return;S.financeMonth=ym;let burden=(l.homeRent||0)+(l.loanPayment||0)+(r.activeLoan?.payment||0),income=(window.LuxLife?.jobs||{})[l.job]||0;if(burden>income*.62&&income){r.bankScore=Math.max(0,(r.bankScore||50)-8);S.bankWarnings++}if(r.businessCash<-25000){S.companyLock=true}if(r.businessCash>=0)S.companyLock=false;if(r.businessCash<-150000||r.status==="bankrupt"){S.companyLock=true;r.status="bankrupt"}save();window.LuxBusinessRisk?.save?.()}
function guardOrders(){let g=window.LuxGameplay;if(!g||g.__v330)return;g.__v330=1;let old=g.order;if(old)g.order=(...a)=>{let r=R();if(S.companyLock||r?.status==="bankrupt")return alert("Bestellung gesperrt: Firmenkonto ist zu stark im Minus oder die Firma ist insolvent.");return old(...a)}}
function labels(){let w=W();if(!w?.THREE||!w?.scene||S.labels)return;S.labels=1;let T=w.THREE;function sign(t,x,z){let c=document.createElement("canvas");c.width=512;c.height=96;let q=c.getContext("2d");q.fillStyle="#111";q.fillRect(0,0,512,96);q.fillStyle="white";q.font="bold 34px Arial";q.textAlign="center";q.fillText(t,256,60);let sp=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),transparent:true}));sp.position.set(x,10,z);sp.scale.set(18,3.4,1);w.scene.add(sp)}sign("🏦 LUX CITY BANK",-108,-15);sign("💼 ARBEITSAMT",-88,42);sign("🏠 WOHNUNGEN",-143,70);sign("🏛 GEMEINDE",-150,20)}
function status(){let h=document.getElementById("hud");if(!h||document.getElementById("work330"))return;let b=document.createElement("button");b.id="work330";b.textContent="ARBEIT";b.onclick=shift;h.appendChild(b)}
function interactionGuard(){let w=W();if(!w||w.__distanceGuard)return;w.__distanceGuard=true;window.LuxNear=(x,z,max=10)=>dist(w.player.position,{x,z})<=max}
setInterval(()=>{finance();guardOrders();labels();status();interactionGuard()},1000);const doors={bakery:{x:-92,z:-85.3},cafe:{x:91,z:-84.3},pub:{x:-91,z:98.2},mill:{x:91,z:101.7},sugar:{x:-92,z:230.2},bottler:{x:92,z:231.7},post:{x:-92,z:-205.3},police:{x:92,z:-207.8},fire:{x:210,z:110.2},rescue:{x:210,z:-77.3},hospital:{x:-210,z:-75.8},bank:{x:-108,z:-15},jobs:{x:-88,z:42},housing:{x:-143,z:70},townhall:{x:-150,z:27},colosseum:{x:195,z:135}};function canInteract(id,max=10){let d=doors[id];return !!d&&!!window.LuxNear?.(d.x,d.z,max)}function requireNear(id,max=10){if(canInteract(id,max))return true;alert("Du bist zu weit weg. Geh direkt zur Tür.");return false}window.LuxSystems330={state:S,shift,finance,doors,near:(x,z,m)=>window.LuxNear?.(x,z,m),canInteract,requireNear,save}})();