(()=>{const K='luxcity_vehicles_v160';let S=Object.assign({owned:[],active:null},JSON.parse(localStorage.getItem(K)||'{}'));const save=()=>localStorage.setItem(K,JSON.stringify(S));const cars={
ev_compact:{name:'E-Kompaktwagen',type:'compact',fuelType:'electric',price:31000},
petrol_compact:{name:'Kompaktwagen Benzin',type:'compact',fuelType:'petrol',price:21000},
diesel_compact:{name:'Kompaktwagen Diesel',type:'compact',fuelType:'diesel',price:24000},
ev_suv:{name:'E-SUV',type:'suv',fuelType:'electric',price:47000},
petrol_suv:{name:'SUV Benzin',type:'suv',fuelType:'petrol',price:39000},
diesel_van:{name:'Lieferwagen Diesel',type:'van',fuelType:'diesel',price:33000}};
for(let v of S.owned){v.type=v.type||'compact';v.fuelType=v.fuelType||v.fuel_type||(v.type==='van'?'diesel':'petrol');v.energy=Number(v.energy??100);v.condition=Number(v.condition??100)}
function buy(k){let m=cars[k];if(!m)return;if(window.LuxLife&&LuxLife.state.cash<m.price)return alert('Nicht genug Geld');if(window.LuxLife)LuxLife.addExpense(m.price);S.owned.push({id:String(Date.now()),catalogKey:k,type:m.type,name:m.name,fuelType:m.fuelType,energy:100,condition:100});save();open()}
function label(f){return f==='electric'?'Elektro':f==='diesel'?'Diesel':'Benzin'}function open(){let m=document.getElementById('modal'),b=document.getElementById('modalBody');if(!m||!b)return;m.hidden=false;b.innerHTML='<h2>Fahrzeuge</h2><p>Wähle zwischen Elektro, Benzin und Diesel.</p>'+Object.entries(cars).map(([k,v])=>'<button data-buy="'+k+'">'+v.name+' · '+label(v.fuelType)+' · '+v.price.toLocaleString('de-DE')+' €</button>').join(' ')+'<h3>Eigene Fahrzeuge</h3>'+S.owned.map((v,i)=>'<div style="padding:7px 0">'+v.name+' · '+label(v.fuelType)+' · '+Math.round(v.energy??100)+'% <button data-use="'+i+'">Auswählen</button></div>').join('');b.querySelectorAll('[data-buy]').forEach(x=>x.onclick=()=>buy(x.dataset.buy));b.querySelectorAll('[data-use]').forEach(x=>x.onclick=()=>{let v=S.owned[Number(x.dataset.use)];S.active=v.id;save();window.LuxPlayerCar710?.applyVehicle?.(v.type);open()})}
function add(){let h=document.getElementById('hud');if(!h||document.getElementById('vehicleBtn'))return;let b=document.createElement('button');b.id='vehicleBtn';b.textContent='AUTO';b.onclick=open;h.appendChild(b)}setInterval(add,1000);window.LuxVehicles={state:S,cars,buy,open,save,get activeVehicle(){return S.owned.find(v=>v.id===S.active)||null}};setTimeout(()=>{let v=S.owned.find(x=>x.id===S.active);if(v)window.LuxPlayerCar710?.applyVehicle?.(v.type)},1200)})();