(()=>{const K='luxcity_vehicles_v160';let S=Object.assign({owned:[],active:null},JSON.parse(localStorage.getItem(K)||'{}'));const save=()=>localStorage.setItem(K,JSON.stringify(S));const DELIVERY={x:-24,z:303,rot:Math.PI/2};const cars={
ev_compact:{name:'E-Kompaktwagen',type:'compact',fuelType:'electric',price:31000},
petrol_compact:{name:'Kompaktwagen Benzin',type:'compact',fuelType:'petrol',price:21000},
diesel_compact:{name:'Kompaktwagen Diesel',type:'compact',fuelType:'diesel',price:24000},
ev_suv:{name:'E-SUV',type:'suv',fuelType:'electric',price:47000},
petrol_suv:{name:'SUV Benzin',type:'suv',fuelType:'petrol',price:39000},
diesel_van:{name:'Lieferwagen Diesel',type:'van',fuelType:'diesel',price:33000}};
for(let v of S.owned){v.type=v.type||'compact';v.fuelType=v.fuelType||v.fuel_type||(v.type==='van'?'diesel':'petrol');v.energy=Number(v.energy??100);v.condition=Number(v.condition??100);if(v.parked_x!=null&&v.parkedX==null)v.parkedX=Number(v.parked_x);if(v.parked_z!=null&&v.parkedZ==null)v.parkedZ=Number(v.parked_z);if(v.parked_rot!=null&&v.parkedRot==null)v.parkedRot=Number(v.parked_rot);v.parkingType=v.parkingType||v.parking_type||null}
function label(f){return f==='electric'?'Elektro':f==='diesel'?'Diesel':'Benzin'}function modal(html){let m=document.getElementById('modal'),b=document.getElementById('modalBody');if(!m||!b)return null;m.hidden=false;m.style.display='block';b.innerHTML=html;return b}
async function buy(k){let m=cars[k];if(!m)return;if(window.LuxVehicleBusiness750&&!window.LuxVehicleBusiness750.nearDealer())return alert('Fahrzeuge kaufst du direkt beim Fahrzeughändler.');if(window.LuxLife&&LuxLife.state.cash<m.price)return alert('Nicht genug Privatgeld.');let rec=null,sb=window.LuxAccount?.sb,uid=window.LuxAccount?.session?.user?.id;
if(sb&&uid){let {data,error}=await sb.from('player_vehicles').insert({owner:uid,kind:m.type,name:m.name,condition:100,energy:100,fuel_type:m.fuelType,parked_x:DELIVERY.x,parked_z:DELIVERY.z,parked_rot:DELIVERY.rot,parking_type:'dealer'}).select('id,kind,name,condition,energy,fuel_type,parked_x,parked_z,parked_rot,parking_type').single();if(!error&&data)rec={id:'server-'+data.id,serverId:data.id,type:data.kind||m.type,name:data.name||m.name,fuelType:data.fuel_type||m.fuelType,energy:Number(data.energy??100),condition:Number(data.condition??100),parkedX:Number(data.parked_x),parkedZ:Number(data.parked_z),parkedRot:Number(data.parked_rot),parkingType:'dealer',parkingLabel:'Auslieferungsplatz Händler'}}
if(!rec)rec={id:String(Date.now()),catalogKey:k,type:m.type,name:m.name,fuelType:m.fuelType,energy:100,condition:100,parkedX:DELIVERY.x,parkedZ:DELIVERY.z,parkedRot:DELIVERY.rot,parkingType:'dealer',parkingLabel:'Auslieferungsplatz Händler'};
if(window.LuxLife)LuxLife.addExpense(m.price);S.owned.push(rec);S.active=rec.id;save();let pc=window.LuxPlayerCar750||window.LuxPlayerCar740;pc?.applyVehicle?.(rec.type);pc?.restoreParked?.(rec);await window.LuxServerAssets740?.refresh?.();openDealer()}
function ownedHtml(){return S.owned.length?S.owned.map((v,i)=>'<div style="padding:9px 0;border-bottom:1px solid #ffffff18"><b>'+v.name+'</b> · '+label(v.fuelType)+' · Zustand '+Math.round(v.condition??100)+'% · '+Math.round(v.energy??100)+'%<br><small>'+(v.parkingLabel||'Kein Stellplatz gespeichert')+'</small> <button data-use="'+i+'">AUSWÄHLEN</button></div>').join(''):'<p>Du besitzt noch kein Fahrzeug.</p>'}
function bindOwned(b){b.querySelectorAll('[data-use]').forEach(x=>x.onclick=()=>{let v=S.owned[Number(x.dataset.use)];S.active=v.id;save();let pc=window.LuxPlayerCar750||window.LuxPlayerCar740;pc?.applyVehicle?.(v.type);pc?.restoreParked?.(v);open()})}
function open(){let b=modal('<h2>🚗 Meine Fahrzeuge</h2><p>Fahrzeuge werden beim Händler gekauft. Hier verwaltest du nur deinen Besitz.</p>'+ownedHtml());if(b)bindOwned(b)}
function openDealer(){if(window.LuxVehicleBusiness750&&!window.LuxVehicleBusiness750.nearDealer())return alert('Geh zum Fahrzeughändler.');let b=modal('<h2>🚘 Lux City Fahrzeughandel</h2><p>Neuwagen · Auslieferung direkt auf dem Händler-Stellplatz.</p>'+Object.entries(cars).map(([k,v])=>'<div style="padding:8px 0;border-bottom:1px solid #ffffff16"><b>'+v.name+'</b><br>'+label(v.fuelType)+' · '+v.price.toLocaleString('de-DE')+' € <button data-buy="'+k+'">KAUFEN</button></div>').join('')+'<h3>Deine Fahrzeuge</h3>'+ownedHtml());if(!b)return;b.querySelectorAll('[data-buy]').forEach(x=>x.onclick=()=>buy(x.dataset.buy));bindOwned(b)}
function add(){let h=document.getElementById('hud');if(!h||document.getElementById('vehicleBtn'))return;let b=document.createElement('button');b.id='vehicleBtn';b.textContent='AUTO';b.onclick=open;h.appendChild(b)}setInterval(add,1000);window.LuxVehicles={state:S,cars,buy,open,openDealer,save,delivery:DELIVERY,get activeVehicle(){return S.owned.find(v=>v.id===S.active)||null}};setTimeout(()=>{let v=S.owned.find(x=>x.id===S.active);if(v)(window.LuxPlayerCar750||window.LuxPlayerCar740)?.applyVehicle?.(v.type)},1200)})();